---
permalink: linux-administration/concept_guidelines_for_thesnapdrive_storagedisconnectcommand.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, disconnect, command, guidelines 
summary: Siga estas directrices al utilizar el comando SnapDrive Storage Disconnect. 
---
= Directrices para el comando SnapDrive Storage Disconnect
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estas directrices cuando utilice `snapdrive storage disconnect` comando:

* Al desconectar un sistema de archivos, SnapDrive para UNIX elimina siempre el punto de montaje.
+
Los hosts Linux le permiten conectar varios sistemas de archivos a un único punto de montaje. Sin embargo, SnapDrive para UNIX requiere un punto de montaje único para cada sistema de archivos. La `snapdrive storage disconnect` se produce un error de comando si se utiliza para desconectar los sistemas de archivos conectados a un único punto de montaje.

* Si utiliza la `-lun` Opción para especificar el nombre de una LUN que sea miembro de un grupo de discos de host o de un sistema de archivos, el `snapdrive storage disconnect` error del comando.
* Si utiliza `-lun` Opción para especificar el nombre del LUN que no se ha detectado mediante software multivía en el host, el `snapdrive storage disconnect` error del comando.



NOTE: `snapdrive storage disconnect` Se produce un error en el comando mientras se usa el LUN de RDM, si el igroup de asignación tiene más de dos nombres de puerto WWPN, en versiones anteriores a SnapDrive 5.2 para UNIX.
