---
permalink: linux-administration/concept_automatic_detection_of_host_entities.html 
sidebar: sidebar 
keywords: snap, snapdrive, detection, host, automatic 
summary: SnapDrive para UNIX detecta automáticamente la configuración de la entidad host para algunos comandos. Unos pocos comandos de almacenamiento de snap solo necesitan el nombre de la entidad de host. En estos casos, no es necesario especificar el tipo de entidad del host. 
---
= Detección automática de entidades host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive para UNIX detecta automáticamente la configuración de la entidad host para algunos comandos. Unos pocos `snap storage` los comandos solo necesitan el nombre de la entidad del host. En estos casos, no es necesario especificar el tipo de entidad del host.

Los siguientes comandos están habilitados para la detección automática:

* `storage delete`
* `storage resize`
* `snap create`
* `snap restore`
* `snap connect`
* `snap list`


Cuando existe la entidad host, SnapDrive para UNIX detecta automáticamente el tipo de entidad host. En este caso, solo se debe proporcionar el nombre de la entidad del host, no es necesario especificar el tipo. La SnapDrive `snap` comandos y algunos `storage` además, los comandos solo necesitan el nombre de la entidad del host, no es necesario especificar el tipo.

La detección automática de comandos tarda más tiempo en SnapDrive 4.1 y versiones posteriores, ya que recopila los detalles de todos los recursos de almacenamiento. Si desea una respuesta más rápida, especifique la especificación del archivo con los comandos de la SnapDrive para UNIX.

Puede habilitar la detección automática para la operación de eliminación de almacenamiento ejecutando el `snapdrive storage delete` comando.

*Ejemplo 1:*

[listing]
----
snapdrive storage delete host_dg my_fs -full
----
En el ejemplo: `host_dg` y.. `my_fs` se detectan automáticamente.

*Ejemplo 2:*

[listing]
----
snapdrive storage delete mydg -fs myfs -full
----
En el ejemplo, la `mydg` el grupo de discos se detecta automáticamente.

Puede habilitar la detección automática para la operación de cambio de tamaño del almacenamiento ejecutando el `snapdrive storage resize` comando.

*Por ejemplo*:

[listing]
----
[root@lnx197-132 ~]# snapdrive storage resize mydg23 -addlun -growby 10m
Auto detecting the type of filespec 'mydg23' in progress ... detected as disk group
        discovering filer LUNs in disk group mydg23...done
        LUN bart:/vol/voldm/mydg23-1_SdLun ... created

        mapping new lun(s) ... done
        discovering new lun(s) ... done.
        initializing LUN(s) and adding to disk group mydg23...done
Disk group mydg23 has been resized
----
Puede activar la detección automática para la operación de creación de instantáneas ejecutando `snapdrive snap create` comando.

*Por ejemplo*:

[listing]
----
root@lnx197-132 ~]# snapdrive snap create mydg22 mydg23 /mnt/mnt12 -snapname new_snap
Auto detecting the type of filespec 'mydg22' in progress ... detected as disk group
Auto detecting the type of filespec 'mydg23' in progress ... detected as disk group
Auto detecting the type of filespec '/mnt/mnt12 ' in progress ... detected as file system

Starting snap create /dev/mapper/mydg22, /dev/mapper/mydg23, /mnt/mnt12
  WARNING:  DO NOT CONTROL-C!
            If snap create is interrupted, incomplete snapdrive
                 generated data may remain on the filer volume(s)
                 which may interfere with other snap operations.
Successfully created snapshot new_snap on bart:/vol/voldm

        snapshot new_snap contains:
        disk group mydg22
        disk group mydg23
        disk group dg121 containing host volumes
                lv121 (filesystem: /mnt/mnt12)
----
Puede activar la detección automática para la operación de conexión a snap mediante la ejecución de `snapdrive snap connect` comando.

*Por ejemplo*:

[listing]
----
[root@lnx197-132 ~]# snapdrive snap connect mydg22 xxx mydg23 yyy -snapname bart:/vol/voldm:snap_1
Auto detecting the type of filespec 'mydg22' in progress ... detected as disk group
Auto detecting the type of filespec 'xxx' in progress ...
        xxx does not exist - Taking xxx as a destination to fspec mydg22Auto detecting the type of filespec 'mydg23' in progress ... detected as disk group
Auto detecting the type of filespec 'yyy' in progress ...
        yyy does not exist - Taking yyy as a destination to fspec mydg23
 connecting mydg22:
        LUN copy mydg22_SdLun_0 ... created
                 (original: bart:/vol/voldm/mydg22_SdLun)

        mapping new lun(s) ... done

 connecting mydg23:
        LUN copy mydg23_SdLun_1 ... created
                 (original: bart:/vol/voldm/mydg23_SdLun)

        mapping new lun(s) ... done
        discovering new lun(s) ... done
        Importing xxx, yyy
Successfully connected to snapshot bart:/vol/voldm:snap_1
        disk group xxx
        disk group yyy
----
Puede habilitar la detección automática para la operación de restauración de snap ejecutando el `snapdrive snap restore` comando.

*Por ejemplo*:

[listing]
----
snapdrive snap restore bart:/vol/voldm/lun44 /mnt/fs3 fs5_SdDg/fs5_SdHv fs4_SdDg -snapname bart:/vol/voldm:toi_snap

        Auto detection of file_spec(s) in progress ...
               - 'bart:/vol/voldm/lun44' detected as LUN.
               - '/mnt/fs3' detected as file system.
               - 'fs5_SdDg/fs5_SdHv' detected as logical volume.
               - 'fs4_SdDg' detected as disk group.
        Starting to restore /dev/mapper/fs4_SdDg, /mnt/fs3, /dev/mapper/fs5_SdDg-fs5_SdHv, bart:/vol/voldm/lun44
         WARNING:  This can take several minutes.
           DO NOT CONTROL-C!
           If snap restore is interrupted, the filespecs
           being restored may have inconsistent or corrupted
           data.
       For detailed progress information, see the log file /var/log/sd-recovery.log
           Importing fs4_SdDg, fs3_SdDg, fs5_SdDg
           Successfully restored snapshot toi_snap on bart:/vol/voldm
       disk group fs4_SdDg containing host volumes
               fs4_SdHv (filesystem: /mnt/fs4)
       disk group fs3_SdDg containing host volumes
               fs3_SdHv (filesystem: /mnt/fs3)
       disk group fs5_SdDg containing host volumes
               fs5_SdHv (filesystem: /mnt/fs5)
       raw LUN: bart:/vol/voldm/lun44
----
SnapDrive no admite la detección automática para las operaciones de conexión rápida y restauración rápida para una especificación de archivo incorrecta.

Puede habilitar la detección automática para la operación de lista de snap ejecutando `snapdrive snap list` comando.

*Por ejemplo*:

[listing]
----
root@lnx197-132 ~]# snapdrive snap list -snapname bart:/vol/voldm:snap_1

snap name                            host                   date         snapped
--------------------------------------------------------------------------------
bart:/vol/voldm:snap_1           lnx197-132.xyz.com Apr  9 06:04 mydg22 mydg23 dg121
[root@lnx197-132 ~]# snapdrive snap list mydg23
Auto detecting the type of filespec 'mydg23' in progress ... detected as disk group

snap name                            host                   date         snapped
--------------------------------------------------------------------------------
bart:/vol/voldm:snap_1           lnx197-132.xyz.com Apr  9 06:04 mydg22 mydg23 dg121
bart:/vol/voldm:all                  lnx197-132.xyz.com Apr  9 00:16 mydg22 mydg23 fs1_SdDg
bart:/vol/voldm:you                  lnx197-132.xyz.com Apr  8 21:03 mydg22 mydg23
bart:/vol/voldm:snap_2                  lnx197-132.xyz.com Apr  8 18:05 mydg22 mydg23
----