---
permalink: linux-administration/concept_guidelines_for_thestorage_connectcommand.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, connect, command, guidelines, lvm 
summary: Debe seguir algunas directrices para utilizar el comando SnapDrive Storage connect. 
---
= Directrices para el comando Storage connect
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe seguir algunas directrices para utilizar el `snapdrive storage connect` comando.

El almacenamiento que incluye entidades de LVM tiene requisitos especiales. Para utilizar la `snapdrive storage connect` Para conectar entidades de LVM, tiene que crear el almacenamiento de modo que cada entidad de la jerarquía del almacenamiento tenga exactamente una instancia de la siguiente entidad. Por ejemplo, puede usar el `snapdrive storage connect` comando para conectar una jerarquía de almacenamiento que tenga un grupo de discos (dg1) con un volumen de host (hostvol1) y un sistema de archivos (fs1). Sin embargo, no puede utilizar la `snapdrive storage connect` comando para conectar una jerarquía que tiene un grupo de discos (dg1) con dos volúmenes host (hostvol1 y hostvol2) y dos sistemas de archivos (fs1 y fs2).

En los hosts Linux, el `snapdrive storage connect` El comando conecta un sistema de archivos creado directamente en una LUN solo cuando se crean particiones en la LUN subyacente.


NOTE: Con SLES10 actualización 2, SnapDrive para UNIX `snapdrive storage connect` y.. `snapdrive storage create` Comando crea un sistema de archivos directamente en una LUN. SnapDrive para UNIX crea un sistema de archivos en el dispositivo sin formato y, a continuación, lo monta.
