---
permalink: linux-administration/reference_host_side_command_lines.html 
sidebar: sidebar 
keywords: snap, snapdrive, host, command, operations 
summary: Los comandos de la SnapDrive para UNIX se usan para las operaciones del lado del host. 
---
= Líneas de comandos del lado del host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los comandos de la SnapDrive para UNIX se usan para las operaciones del lado del host.

En la siguiente tabla se proporcionan varias opciones de línea de comandos para las operaciones del lado del host.

|===
| Funcionamiento | Opción de línea de comandos 


 a| 
Conexión del host
 a| 
`snapdrive host connect -lun _long_lun_name_ [_lun_name ..._] [-vmtype _type_]`



 a| 
`snapdrive host connect -fs _file_spec_ -nolvm -lun _long_lun_name_ [-nopersist][-mntopts options] [-fstype _type_] [-vmtype _type_]`



 a| 
`snapdrive host connect -fs _file_spec_ -hostvol _file_spec_ -lun _long_lun_name_ [_lun_name_][-nopersist] [-mntopts _options_][-vmtype _type_]`



 a| 
Desconexión del host
 a| 
`snapdrive host disconnect-lun _long_lun_name_ [_lun_name..._] [-vmtype _type_]`



 a| 
`snapdrive host disconnect {-vg | -dg | -fs | -lvol | -hostvol} _file_spec_[_file_spec ..._][{-vg | -dg | -fs | -lvol | -hostvol} _file_spec_ [_file_spec ..._]...] [-full] [-fstype _type_] [-vmtype _type_]`

|===