---
permalink: linux-administration/reference_command_line_arguments.html 
sidebar: sidebar 
keywords: snap, snapdrive, command, argument, format, copy, snapshot 
summary: SnapDrive para UNIX toma argumentos en un formato específico. 
---
= Argumentos de la línea de comandos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive para UNIX toma argumentos en un formato específico.

En la siguiente tabla se describen los argumentos que se pueden especificar con las palabras clave.

Utilice el formato `snapdrive type_name operation_name [<keyword/option> <arguments>]`; Por ejemplo, si desea crear una copia Snapshot llamada `snap_hr` desde el sistema de archivos host `/mnt/dir`, debe introducir la siguiente línea de comandos:

`*snapdrive snap create -fs/mnt/dir -snapname _snap_hr*`.

|===
| Argumento | Descripción 


 a| 
dest_fspec
 a| 
Nombre a través del cual se podrá acceder la entidad de destino después de que estén conectados sus grupos de discos o LUN.



 a| 
dgname
 a| 
El nombre de un grupo de discos o de volúmenes.



 a| 
d_lun_name
 a| 
Permite especificar un nombre de destino que utiliza SnapDrive para UNIX para que la LUN esté disponible en la copia recién conectada de la copia Snapshot.



 a| 
nombre_de_archivo
 a| 
El nombre de un sistema de almacenamiento.



 a| 
ruta_del_filer
 a| 
Nombre de ruta a un objeto del sistema de almacenamiento. Este nombre puede contener el nombre y el volumen del sistema de almacenamiento, pero no es necesario que SnapDrive para UNIX pueda usar valores predeterminados para los componentes que faltan en función de los valores proporcionados en los argumentos anteriores. A continuación se muestran ejemplos de nombres de ruta:

* `test_filer:/vol/vol3/qtree_2`
* `/vol/vol3/qtree_2`
* `qtree_2`




 a| 
especificación_archivo
 a| 
El nombre de una entidad de almacenamiento, como un volumen de host, LUN, disco o grupo de volúmenes, un sistema de archivos o un árbol de directorios de NFS.

En general, el argumento file_spec se utiliza como una de las siguientes opciones:

* Un objeto que desea que SnapDrive para UNIX realice una copia Snapshot de o restaurar desde una copia Snapshot
* Un objeto que se desea crear o utilizar al aprovisionar almacenamiento


No es necesario que los objetos sean del mismo tipo. Si se suministran varios volúmenes de host, todos deben pertenecer al mismo administrador de volúmenes.

Si se proporcionan valores para este argumento que se resuelven en grupos de discos o volúmenes de hosts redundantes, el comando falla.

Ejemplo de uso incorrecto: En este ejemplo se supone que dg1 tiene volúmenes host hv1 y hv2, con sistemas de archivos fs1 y fs2. Como resultado, se podrían producir errores en los siguientes argumentos porque involucran grupos de discos redundantes o volúmenes de host.

`-dg _dg1_ -hostvoldg1/hv1`

`-dg _dg1_`

`-fs/fs1`

`-hostvol dg1/hv1 -fs /fs1`

Ejemplo de uso correcto: Este ejemplo muestra el uso correcto de este argumento.

`-hostvoldg1/hv1dg1/hv2`

`-fs/fs1/fs2`

`-hostvoldg1/hv1 -fs/fs2`



 a| 
fspec_set
 a| 
Se utiliza con el comando snap connect para identificar:

* Una entidad LVM del host
* Un sistema de archivos contenido en un LUN


El argumento también permite especificar un conjunto de nombres de destino que utiliza SnapDrive para UNIX cuando hace que la entidad esté disponible en la copia Snapshot recién conectada.

El formato para fspec_set es: `{ -vg | -dg | -fs | -lvol | -hostvol } _src_fspec_ [_dest_fspec_] [{ -destdg | -destvg } _dg_name_] [{ - destlv | -desthv } _lv_name_]`



 a| 
host_lvm_fspec
 a| 
Permite especificar si desea crear un sistema de archivos, un volumen lógico o un grupo de discos cuando se ejecuta el comando Storage create. Este argumento puede tener cualquiera de los tres formatos descritos en el siguiente. El formato que utilice dependerá de la entidad que desee crear.


NOTE: La `-dg` y.. `-vg` las opciones son sinónimos que reflejan el hecho de que algunos sistemas operativos hacen referencia a grupos de discos, mientras que otros hacen referencia a grupos de volúmenes. Además, `-lvol` y.. `-hostvol` son también sinónimos. En esta guía se utiliza -dg para hacer referencia tanto a grupos de discos como a grupos de volúmenes y. `-hostvol` para hacer referencia tanto a los volúmenes lógicos como a los volúmenes de host.



 a| 
Para crear un sistema de archivos, utilice este formato: -Fs file_spec ``[-fstype _type_] [-fsopts _options_] [-hostvol _file_spec_] [-dg _dg_name_] To create a logical or host volume, use this format: [-hostvol _file_spec_] [-dg _dg_name_] | -hostvol` Para crear un disco o grupo de volúmenes, use el siguiente formato: File_spec `[-dg _dg_name_] | -dg _dg_name_`

Debe asignar un nombre a la entidad de nivel superior que se va a crear. No es necesario proporcionar nombres para ninguna entidad subyacente. Si no proporciona nombres para las entidades subyacentes, SnapDrive para UNIX los crea con nombres generados internamente.

Si especifica que SnapDrive para UNIX crea un sistema de archivos, tiene que especificar un tipo que SnapDrive para UNIX admite con el LVM del host. Estos tipos incluyen `ext4` o. `ext3`

La opción `-fsopts` se utiliza para especificar las opciones que se deben pasar a la operación host que crea el nuevo sistema de archivos; por ejemplo, `mkfs`.



 a| 
nombre_ig
 a| 
El nombre de un iGroup.



 a| 
ruta_de_filer_larga
 a| 
Un nombre de ruta que incluye el nombre del sistema de almacenamiento, el nombre del volumen y, posiblemente, otros elementos de directorio y archivo dentro de ese volumen. A continuación se muestran ejemplos de nombres largos de ruta:

`test_filer:/vol/vol3/qtree_2`

`10.10.10.1:/vol/vol4/lun_21`



 a| 
nombre_lun_largo
 a| 
Un nombre que incluye el nombre del sistema de almacenamiento, el volumen y el nombre de LUN. A continuación se muestra un ejemplo de un nombre de LUN largo:

`test_filer:/vol/vol1/lunA`



 a| 
long_snap_name
 a| 
Un nombre que incluye el nombre del sistema de almacenamiento, el volumen y el nombre de la copia de Snapshot. Lo siguiente es un ejemplo de un nombre de copia Snapshot largo: `test_filer:/vol/account_vol:snap_20040202`

Con la `snapdrive snap show` y.. `snapdrive snap delete` Comandos, puede usar el carácter de asterisco (*) como comodín para coincidir con cualquier parte del nombre de una copia de Snapshot. Si usa un carácter comodín, debe colocarlo al final del nombre de la copia Snapshot. SnapDrive para UNIX muestra un mensaje de error si utiliza un comodín en cualquier otro punto del nombre.

Ejemplo: En este ejemplo se utilizan comodines con ambos `snap show` y la `snap delete` comando: `snap show myfiler:/vol/vol2:mysnap*`

`myfiler:/vol/vol2:/yoursnap* snap show myfiler:/vol/vol1/qtree1:qtree_snap* snap delete 10.10.10.10:/vol/vol2:mysnap* 10.10.10.11:/vol/vol3:yoursnap* hersnap`

Limitación de caracteres comodín: No se puede introducir un comodín en medio de un nombre de copia Snapshot. Por ejemplo, la siguiente línea de comandos genera un mensaje de error porque el carácter comodín está en medio del nombre de copia Snapshot: `banana:/vol/vol1:my*snap`



 a| 
nombre_lun
 a| 
El nombre de una LUN. Este nombre no incluye el sistema de almacenamiento y el volumen donde se encuentra el LUN. A continuación se muestra un ejemplo de un nombre de LUN: Luna



 a| 
ruta
 a| 
Cualquier nombre de ruta.



 a| 
cadena_prefijo
 a| 
el prefijo que se utiliza en la generación de nombres del clon del volumen



 a| 
s_lun_name
 a| 
Indica una entidad LUN que está capturada en la copia Snapshot especificada por `_long_snap_name_`.

|===
*Información relacionada*

xref:reference_storage_provisioning_command_lines.adoc[Líneas de comandos de aprovisionamiento de almacenamiento]
