---
permalink: linux-administration/task_creating_a_filesystem_on_a_lunand_setting_up_thelun_automatically.html 
sidebar: sidebar 
keywords: snap, snapdrive, lun, create, file 
summary: Puede crear un sistema de archivos en una LUN mediante SnapDrive para UNIX. SnapDrive para UNIX crea automáticamente el LUN asociado. 
---
= Crear un sistema de archivos en una LUN y configurar la LUN de forma automática
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear un sistema de archivos en una LUN mediante SnapDrive para UNIX. SnapDrive para UNIX crea automáticamente el LUN asociado.

.Pasos
. En la línea de comandos, introduzca el siguiente comando:
+
`*snapdrive storage create -fs _file_spec_ -nolvm [-fstype type] [-fsopts options] [-mntopts options] [-nopersist] -filervol _long_filer_path_ -lunsize size [-igroup _ig_name[ig_name ...]]_ [{-reserve | -noreserve }]*`

+
SnapDrive para UNIX crea el sistema de archivos que especifique y crea un LUN para él en el sistema de almacenamiento que especifique. Realiza todas las tareas asociadas con la preparación y detección del host para las LUN, así como la asignación y conexión de las LUN a la entidad del host.





== Ejemplos:

*Crear un sistema de archivos de 100 MB directamente en una LUN:*

[listing]
----
# snapdrive storage create -fs /mnt/acct1 -filervol acctfiler:/vol/vol1 -lunsize 100m -nolvm
----
*Creación de un sistema de archivos en un LUN RAW sin ningún gestor de volúmenes:*

[listing]
----
# snapdrive storage create -fs /mnt/vxfs2 -fstype vxfs -lun
snoopy:/vol/vol1/lunVxvm2 -lunsize 50m -nolvm
LUN snoopy:/vol/vol1/lunVxvm2 ... created
mapping new lun(s) ... done
discovering new lun(s) ... done
LUN to device file mappings:
- snoopy:/vol/vol1/lunVxvm2 => /dev/vx/dmp/Disk_1
file system /mnt/vxfs2 created
----
*Creación de un sistema de archivos en un LUN de RDM sin ningún gestor de volúmenes:*

[listing]
----
# snapdrive storage create -fs /mnt/fs -fstype ext3 -lun
lech:/vol/vol_1/lun1 -lunsize 50m -nolvm
LUN lech:/vol/vol1/lun1 ... created
exporting new lun(s) to Guest OS ... done
discovering new lun(s) ... done
LUN to device file mappings:
- lech:/vol/vol1/lun1 => /dev/sdb
file system /mnt/fs created
----