---
permalink: linux-administration/task_creating_a_filesystem_on_a_lunand_specifying_thelun.html 
sidebar: sidebar 
keywords: snap, snapdrive, lun, file, create 
summary: Puede crear un sistema de archivos en una LUN y especificar las LUN que se crean como parte del mismo. 
---
= Crear un sistema de archivos en una LUN y especificar la LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear un sistema de archivos en una LUN y especificar las LUN que se crean como parte del mismo.

.Pasos
. Use el siguiente formato del comando para completar esta operación:
+
`*snapdrive storage create _-fsfile_spec_ -nolvm [-fstype type] [-vmtype _type_] [-fsopts _options_] [-mntopts _options_] [-nopersist] -lun _long_lun_name_ -lun _size sizeig_name_ [_ig_name..._]] [{ -reserve | -noreserve }]*`

+
SnapDrive para UNIX crea el sistema de archivos en el sistema de almacenamiento, el volumen y la LUN especificados. Realiza todas las tareas asociadas con la preparación y detección del host para las LUN, así como la asignación y conexión de las LUN a la entidad del host.





== Ejemplo: Crear un sistema de archivos de 100 MB en luna en acctfiler:/vol/vol1

`# snapdrive storage create -fs /mnt/acct1 -lun acctfiler:/vol/vol1/luna -lunsize 100m -nolvm`
