---
permalink: linux-administration/task_starting_the_volume_or_lun_clone_split_start.html 
sidebar: sidebar 
keywords: snap, snapdrive, clone, lun, split, volume 
summary: Es posible iniciar una operación de división de clones de volumen o LUN. 
---
= Iniciar el clon de volumen o la división de clones de LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible iniciar una operación de división de clones de volumen o LUN.

.Pasos
. Introduzca el siguiente comando para iniciar una división de clones de volumen o LUN.
+
`*# snapdrive clone split start [-lun] _long_lun_name_ [_long_lun_name..._] | [{-dg | -vg | -fs | -hostvol | -lvol} _file_spec_ [_file_spec ..._]] [-force][-noprompt] [-dump | -dumpall]*`

+
Cuando el estado del almacenamiento muestre como NO DISPONIBLE, pueden utilizarse las siguientes opciones.

+
** Puede utilizar el `-force` opción para iniciar la operación de división de clones de forma forzada y recibir un mensaje de confirmación de que se ha iniciado la operación.
** Puede utilizar el `-noprompt` junto con `-force` opción para iniciar la operación de inicio de división de clones sin recibir ningún mensaje de confirmación.





NOTE: Cuando inicia otra operación de división de clones poco después de detener una operación de división de clones en curso, es posible que se produzca un error en la operación. Este problema puede ocurrir si el retraso entre el inicio y la detención de la operación de división de clones no es suficiente para permitir que el sistema de almacenamiento sincronice la operación de detención.

En el ejemplo siguiente, se muestra cómo dividir un clon de volumen:

[listing]
----
# snapdrive clone split start -fs /mnt/my_mnt4_0 /mnt/my_mnt3_0
Resource    Container  Required Available Storage
                       Space(MB)Space(MB) Status
--------------------------------------------------
/mnt/my_mnt4_0 f3050-220 3295   66033 AVAILABLE
             -111:aggr0
/mnt/my_mnt3_0 f3050-220  293   37707 AVAILABLE
             -112:aggr1

Job ID: B265Dbv8gh
Clone-Split for "/mnt/my_mnt4_0" is started
Clone-Split for "/mnt/my_mnt3_0" is started
----
En el ejemplo siguiente se muestra cómo dividir un clon mediante el `-force` opción:

[listing]
----
# snapdrive clone split start -fs /mnt/my_mnt5 /mnt/my_mnt6 -force
Resource    Container Required  Available Storage
                      Space(MB) Space(MB) Status
----------------------------------------------------
/mnt/my_mnt5 f3050-220 1198   20033   AVAILABLE
             -111:aggr0
/mnt/my_mnt6 f3050-220  3294  2196  NOT AVAILABLE
             -112:aggr1
Not enough space available for Clone-Split.  Do you want to continue (y/n)?y
Clone-Split for "/mnt/my_mnt5" is started
Clone-Split for "/mnt/my_mnt6" is started
----
En el ejemplo siguiente se muestra cómo iniciar directamente un clon mediante el `-noprompt` opción que significa que no hay ningún mensaje de confirmación:

[listing]
----
# snapdrive clone split start -fs /mnt/my_mnt5 /mnt/my_mnt6 -force -noprompt
Resource    Container  Required  Available Storage
                       Space(MB) Space(MB) Status
-----------------------------------------------------
/mnt/my_mnt5 f3050-220  1198     20033   AVAILABLE
             -111:aggr0
/mnt/my_mnt6 f3050-220  3294     2196  NOT AVAILABLE
             -112:aggr1
Clone-Split for "/mnt/my_mnt5" is started
Clone-Split for "/mnt/my_mnt6" is started
----