---
permalink: linux-administration/task_adding_sd_hostname_to_the_storage_system.html 
sidebar: sidebar 
keywords: snap, snapdrive, sd, hostname, storage, manager, operations, administrator 
summary: El administrador de la consola de Operations Manager puede crear el usuario de host sd en el sistema de almacenamiento usando la consola de Operations Manager. Una vez realizados los pasos, el administrador de la consola de Operations Manager debe enviar manualmente las credenciales al administrador de SnapDrive para UNIX. Puede utilizar cualquier nombre en lugar de sd-hostname; sin embargo, es mejor usar sd-hostname. 
---
= Incorporación de sd-hostname al sistema de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El administrador de la consola de Operations Manager puede crear el usuario de host sd en el sistema de almacenamiento usando la consola de Operations Manager. Una vez realizados los pasos, el administrador de la consola de Operations Manager debe enviar manualmente las credenciales al administrador de SnapDrive para UNIX. Puede utilizar cualquier nombre en lugar de sd-hostname; sin embargo, es mejor usar sd-hostname.

. Obtenga la contraseña raíz del sistema de almacenamiento y almacene la contraseña.
+
Para agregar la contraseña para el sistema de almacenamiento, seleccione *Administración* > *sistema de almacenamiento*.

. Cree un usuario de sd-hostname para cada sistema UNIX.
. Asigne capacidades `api-*` y.. `login-*` a una función, como sd-role.
. Incluya esta función (sd-role) en un nuevo grupo de usuarios, como sd-usergroup.
. Asocie este grupo de usuarios (sd-usergroup) al usuario sd-hostname del sistema de almacenamiento.

