---
permalink: linux-administration/task_enabling_multipathing.html 
sidebar: sidebar 
keywords: snap, snapdrive, multipathing, enable, hba 
summary: Para utilizar la multivía en SnapDrive para UNIX, debe completar los pasos que incluyen la instalación e inicio de HBA. Si utiliza una solución multivía que no sea de NetApp, debe descargar el software y el paquete de aplicaciones del sitio web del proveedor de HBA. 
---
= Habilitando el acceso multivía
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para utilizar la multivía en SnapDrive para UNIX, debe completar los pasos que incluyen la instalación e inicio de HBA. Si utiliza una solución multivía que no es de NetApp, debe descargar el software y el paquete de aplicaciones del sitio web del proveedor de HBA.

El sistema debe ejecutar versiones actuales de los componentes del sistema FC e iSCSI.

http://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"]

.Pasos
. Instale los HBA admitidos antes de instalar el software de utilidades de host adecuado.
+

NOTE: SnapDrive para UNIX admite HBA de varios proveedores.

. Inicie el servicio HBA.
+
Si el servicio HBA no está en ejecución, se muestra el siguiente mensaje de error cuando se ejecutan comandos de SnapDrive para UNIX, como `snapdrive storage create` y.. `snapdrive config prepare luns`:

+
[listing]
----
0001-876 Admin error: HBA assistant not found
----
+
Debe comprobar que la cantidad necesaria de rutas está en funcionamiento y en funcionamiento. Puede verificar las rutas utilizando el `sanlun` Utilidad, que se incluye con el software Host Utilities. Por ejemplo, en la configuración multivía de FC, puede utilizar el `sanlun fcp show adapter -v` comando.

+
En el siguiente ejemplo, hay dos puertos HBA (fcd0 y fcd1) conectados al host que están operativos (estado del puerto). Solo puede tener un HBA o iSCSI iniciador y debe configurar la multivía proporcionando más de una ruta a las LUN de destino.

+
[listing]
----
# sanlun fcp show adapter -v
adapter name: fcd0
WWPN: 50060b000038c428
WWNN: 50060b000038c429
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 1 of 2
port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd0
adapter name: fcd1
WWPN: 50060b000038c42a
WWNN: 50060b000038c42b
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 2 of 2 port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd1
----
+
Si la función multivía está habilitada en un host, hay varias rutas visibles para el mismo LUN. Puede utilizar el `sanlun lun show all` comando para comprobar las rutas. En el ejemplo siguiente, puede encontrar varias rutas a la misma LUN (`fish: /vol/vol1/lun`):

+
[listing]
----
 [root@lnx221-75 ~]# sanlun lun show
filer:        lun-pathname device filename adapter protocol lun size lun state
f960-221-167: /vol/vol1/lun1 /dev/sdd host5 FCP 100m (104857600)      GOOD
f960-221-167: /vol/vol1/lun1 /dev/sdc host6 FCP 100m (104857600)      GOOD
----
. Si SnapDrive es compatible con una solución multivía de terceros para UNIX o Host Utilities, descargue el paquete de software del controlador HBA y el paquete de aplicaciones del sitio web del proveedor de HBA.*QLogic*: Para los HBA QLogic, vaya a. http://support.qlogic.com/[]. En modelos OEM, seleccione NetApp. Busque la versión del controlador que aparece en la matriz de soporte y descárguela. *Emulex:* para HBA Emulex, vaya a. http://www.emulex.com/ts/index.html[]. En Downloads, seleccione NetApp. Busque la versión del controlador que aparece en la matriz de soporte y descárguela. Descargue también el paquete de aplicaciones Emulex desde el mismo lugar.
+
Si utiliza un adaptador QLogic con conectividad FC, descargue el script de nueva detección de QLogic del sitio web de QLogic y cópielo en la `/root` ruta (por ejemplo, `/root/dynamic-lun-rescan.sh`). El script de Qlogic RESCAN solicita la confirmación del usuario; SnapDrive for UNIX podría detenerse de forma indefinida en esta fase de confirmación. Para evitar esta confirmación, configure la variable `_QL_DISABLE_WARNING_` para `1` en el script.

+
Las versiones anteriores de SnapDrive para UNIX utilizaba secuencias de comandos SCSI específicas del proveedor para analizar las LUN a través de FC y, de este modo, copiar el script específico del proveedor al `/root/dynamic-lun-rescan.sh`. Esto fue puesto a disposición hasta RHEL 5U3.

+
Para RHEL 5U4/ SLES 10SP2 y versiones posteriores, la secuencia de comandos RESCAN está disponible actualmente en la `/usr/bin` directorio. En caso de que el script de reexploración no esté disponible en el directorio, está presente junto con el `sg3_utils` paquete.

+

NOTE: Debe asegurarse de que el `sg3_utils` y.. `sg3_utils-libs` Hay bibliotecas disponibles para las versiones Red Hat Enterprise Linux (RHEL) y Oracle Enterprise Linux (OEL). Sin embargo, la `sg3_utils` Las bibliotecas están disponibles para la versión de SUSE Linux Enterprise Server (SLES) en `scsci utility.rpm` paquete.

. En una configuración FC, dividir en zonas los puertos HBA del host y los puertos de destino mediante la configuración de la división en zonas del switch.
. Instalar y configurar el switch FC apropiado.
. Comprobar los requisitos de la pila de SnapDrive para UNIX.
. Instalar o actualizar SnapDrive para UNIX.
. Comprobar la instalación de SnapDrive para UNIX.
. Localice el `snapdrive.conf` ruta del archivo.
. Configure las siguientes variables de configuración en el `snapdrive.conf` archivo:
+
** `_multipathing-type_`
** `_default-transport_`
** `_fstype_`
** `_vmtype_`
+
Para cada host, el tipo multivía, el tipo de transporte, el sistema de archivos y el tipo de gestor de volúmenes dependen unos de otros. La siguiente tabla describe todas las combinaciones posibles:

+
|===
| Plataforma host | Tipo de transporte predeterminado | Tipo de acceso múltiple | tipo fstype | vmtype 


 a| 
Linux
 a| 
iscsi
 a| 
nativempio
 a| 
ext4 o ext3
 a| 
lvm



 a| 
iscsi
 a| 
ninguno
 a| 
ext4 o ext3
 a| 
lvm



 a| 
FCP
 a| 
ninguno
 a| 
ext4 o ext3
 a| 
lvm



 a| 
FCP
 a| 
nativempio
 a| 
ext4 o ext3
 a| 
lvm

|===
+
La tabla anterior muestra los valores admitidos de `_multipathing-type_`, `_default-transport_`, `_fstype_`, y. `_vmtype_` variables de configuración.

+

NOTE: Si el protocolo de transporte es `iSCSI`, y el tipo de acceso múltiple está establecido como `none`, Debe detener el daemon multipath y ejecutar los comandos SnapDrive para UNIX.



. Guarde la `snapdrive.conf` archivo.
+
SnapDrive para UNIX comprueba automáticamente este archivo cada vez que se inicia. Debe reiniciar el daemon SnapDrive para UNIX para que los cambios surtan efecto.



*Información relacionada*

xref:concept_snaprestore_and_snapconnect_operations_do_not_work_in_linux_after_multipathing_migration.adoc[Las operaciones de SnapRestore y Snapconnect no funcionan en Linux tras la migración de tipo multivía]

http://mysupport.netapp.com["Soporte de NetApp"]

https://mysupport.netapp.com/NOW/products/interoperability["Interoperabilidad de NetApp"]

https://library.netapp.com/ecm/ecm_download_file/ECMLP2547936["Guía de instalación de Linux Unified Host Utilities 7.1"]
