---
permalink: linux-installation-7mode/task_connecting_linux_host_to_the_storage_system.html 
sidebar: sidebar 
keywords: snap, snapdrive, connect, linux, host, storage, system 
summary: Para tener éxito en sus operaciones con SnapDrive para UNIX, debe configurar el sistema de almacenamiento antes de conectarlo al host Linux. 
---
= Conectar los hosts Linux a los sistemas de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para tener éxito en sus operaciones con SnapDrive para UNIX, debe configurar el sistema de almacenamiento antes de conectarlo al host Linux.

El nombre del sistema de almacenamiento debe estar registrado con un servidor de servicio de nombres de dominio (DNS) en la red o en `/etc/hosts` archivo.

.Pasos
. Cree un usuario en el sistema de almacenamiento:
+
`*snapdrive config set _user_name storage_system_name_*`

. Vea los usuarios asociados con el sistema de almacenamiento y obtenga el nombre de usuario o los detalles de la pareja del sistema de almacenamiento:
+
`*snapdrive config list*`

+
El comando muestra el nombre de usuario o las parejas del sistema de almacenamiento de todos los sistemas que tienen los usuarios especificados en SnapDrive para UNIX.

. Si el sistema de almacenamiento tiene varias interfaces de datos, configure la interfaz de datos para la nueva interfaz de gestión:
+
`*snapdrive config set -mgmtpath _management_interface_path data_interface_path_*`

. Compruebe que todas las interfaces de gestión y datos están configuradas correctamente:
+
`*snapdrive config list -mgmtpath*`


