---
permalink: aix/concept_access_permissions_on_a_storage_system.html 
sidebar: sidebar 
keywords: snap, snapdrive, access, permissions, storage, system 
summary: Los permisos de acceso indican si un host puede realizar ciertas operaciones de copia de Snapshot y almacenamiento. Los permisos de acceso no afectan ninguna de las operaciones de la lista de almacenamiento o la visualización de SnapDrive. SnapDrive permite especificar los permisos de acceso para cada host en un archivo que reside en el sistema de almacenamiento. 
---
= Permisos de acceso en un sistema de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los permisos de acceso indican si un host puede realizar ciertas operaciones de copia de Snapshot y almacenamiento. Los permisos de acceso no afectan ninguna de las operaciones de la lista de almacenamiento o la visualización de SnapDrive. SnapDrive permite especificar los permisos de acceso para cada host en un archivo que reside en el sistema de almacenamiento.

También puede especificar la acción que debe realizar SnapDrive cuando no se encuentra un archivo de permisos para un host especificado. Puede especificar la acción estableciendo el valor en `snapdrive.conf` archivo de configuración para `_all-access-if-rbac-unspecified_`. También se puede habilitar o deshabilitar el acceso al sistema de almacenamiento si se modifican los permisos de acceso.


NOTE: En SnapDrive 4.0 para UNIX y versiones posteriores, es posible realizar operaciones de almacenamiento según las capacidades de control de acceso basado en roles.
