---
permalink: aix/concept_example_of_an_autosupport_message.html 
sidebar: sidebar 
keywords: snap, snapdrive, example, autosupport, message, support 
summary: SnapDrive para UNIX proporciona ejemplos para diferentes situaciones. El contenido de un mensaje de AutoSupport en todos los ejemplos es esencialmente el mismo independientemente del sistema operativo. 
---
= Ejemplos de mensajes de AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive para UNIX proporciona ejemplos para diferentes situaciones. El contenido de un mensaje de AutoSupport en todos los ejemplos es esencialmente el mismo independientemente del sistema operativo.

Ejemplo: La adición de un nuevo sistema de almacenamiento

El siguiente ejemplo es un mensaje enviado desde un host llamado `_aix207-116_`:

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="3"
        category="ohio configured"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp"
----
Ejemplo: Reiniciar el daemon

SnapDrive para UNIX envía el siguiente mensaje de AutoSupport al sistema de almacenamiento cuando reinicia el daemon:

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="2"
        category="daemon restarted"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp"
----
SnapDrive para UNIX envía el siguiente mensaje de AutoSupport al sistema de almacenamiento cuando falla una operación de conexión de almacenamiento:

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="4"
        category="storage connect failed"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp,1384: LUN /vol/vol0/test1 on storage system ohio already mapped to initiators in igroup aix207-116_fcp_SdIg at ID 0."/
----
SnapDrive para UNIX envía el siguiente mensaje de AutoSupport al sistema de almacenamiento cuando una `snap create` la operación se realiza correctamente:

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="5"
        category="snap create successful"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp, snapshot_name=snap1"
----