---
permalink: aix/concept_command_syntax_to_increase_the_sizeof_the_storage.html 
sidebar: sidebar 
keywords: snap, snapdrive, command, syntax, increase, size, storage 
summary: Para aumentar el tamaño del almacenamiento, debe conocer la sintaxis correcta que desea utilizar. 
---
= Sintaxis de comandos para aumentar el tamaño del almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para aumentar el tamaño del almacenamiento, debe conocer la sintaxis correcta que desea utilizar.

`*snapdrive storage resize -dg _file_spec_ { -growby | -growto } size [-addlun [-igroup _ig_name_ [_ig_name_ ...]]] [{ -reserve | - noreserve}]] [-fstype _type_] [-vmtype _type_]*`

[NOTE]
====
No puede utilizar el `snapdrive storage resize` comando para reducir el tamaño de una entidad. Con este comando, solo puede aumentar el tamaño.

La `snapdrive storage resize` el comando no admite directamente en los volúmenes lógicos ni en los sistemas de archivos. Por ejemplo, no puede usar el `snapdrive storage resize` Comando para cambiar el tamaño de un sistema de archivos en una LUN.

*Resultado*: Este comando aumenta el tamaño de la entidad de almacenamiento (volumen lógico o grupo de discos) por una de las siguientes opciones:

* Adición de bytes a almacenamiento (`-growby`).
* Se debe aumentar el tamaño hasta el tamaño de byte especificado (`-growto`).


====