---
permalink: aix/reference_error_message_values.html 
sidebar: sidebar 
keywords: snap, snapdrive, error, message, value 
summary: Es útil conocer algunos de los mensajes de error más comunes que se pueden ver al utilizar SnapDrive para UNIX y saber cómo afrontarlos. 
---
= Valores de mensajes de error
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es útil conocer algunos de los mensajes de error más comunes que se pueden ver al utilizar SnapDrive para UNIX y saber cómo afrontarlos.

En la siguiente tabla, se proporciona información detallada sobre los errores más comunes que se pueden encontrar al utilizar SnapDrive para UNIX:

[cols="15,20,15,25,40"]
|===
| Código de error | Código de retorno | Tipo | Mensaje | Solución 


| `0000-001` | NA | Admin | `Datapath has been configured for the storage system <STORAGE-SYSTEM-NAME>. Please delete it using snapdrive config delete -mgmtpath command and retry.` | Antes de eliminar el sistema de almacenamiento, elimine la ruta de gestión configurada para el sistema de almacenamiento mediante el `snapdrive config delete -mgmtpath` comando. 


| `0001-242` | NA | Admin | `Unable to connect using https to storage system: 10.72.197.213. Ensure that 10.72.197.213 is a valid storage system name/address, and if the storage system that you configure is running on a Data ONTAP operating in 7-Mode, add the host to the trusted hosts (options trusted.hosts) and enable SSL on the storage system 10.72.197.213 or modify the snapdrive.conf to use http for communication and restart the snapdrive daemon. If the storage system that you configure is running on clustered Data ONTAP, ensure that the Vserver name is mapped to IP address of the Vserver's management LIF.`  a| 
Compruebe las siguientes condiciones:

* Asegúrese de que el sistema de almacenamiento que está conectado sea un sistema de almacenamiento válido.
* Si el sistema de almacenamiento que intenta configurar está ejecutándose en Data ONTAP que funciona en 7-Mode, añada lo mismo a los hosts de confianza y habilite SSL en el sistema de almacenamiento o modifique el `snapdrive.conf` Archivo para utilizar HTTP para la comunicación; a continuación, reinicie el daemon SnapDrive.
* Si el sistema de almacenamiento que intenta configurar se está ejecutando en Clustered Data ONTAP, asegúrese de que el nombre del Vserver esté asignado a la dirección IP de la interfaz lógica de gestión (LIF) del Vserver.




| `0003- 004` | NA | Admin | `Failed to deport LUN <LUN-NAME> on storage system <STORAGE-SYSTEM-NAME> from the Guest OS. Reason: No mapping device information populated from CoreOS` | Esto sucede cuando ejecuta el `snapdrive snap disconnect` en el sistema operativo invitado. Compruebe si hay alguna asignación de LUN de RDM en el servidor ESX o en la entrada de RDM obsoleta en el servidor ESX. Elimine la asignación de RDM manualmente tanto en el servidor ESX como en el sistema operativo invitado. 


| `0001- 019` | 3 | Comando | `invalid command line -- duplicate filespecs: <dg1/vol2 and dg1/vol2>`  a| 
Esto sucede cuando el comando ejecutado tiene varias entidades de host en el mismo volumen de host.

Por ejemplo, el comando especificó explícitamente el volumen de host y el sistema de archivos en el mismo volumen de host.

Complete los siguientes pasos:

. Quite todas las instancias duplicadas de las entidades de host.
. Vuelva a ejecutar el comando.




| `0001-023` | 11 | Admin | `Unable to discover all LUNs in Disk Group dg1.Devices not responding: dg1 Please check the LUN status on the storage system and bring the LUN online if necessary or add the host to the trusted hosts (options trusted.hosts) and enable SSL on the storage system or retry after changing snapdrive.conf to use (http/https) for storage system communication and restarting snapdrive daemon.`  a| 
Esto ocurre cuando se produce un error en una consulta de SCSI del dispositivo. Una consulta SCSI del dispositivo puede fallar por varios motivos.

Siga estos pasos:

. Configure la variable de configuración device-retries en un valor más alto.
+
Por ejemplo, configúrelo en 10 (el valor predeterminado es 3) y vuelva a ejecutar el comando.

. Utilice la `snapdrive storage show` comando con la opción -all para obtener información sobre el dispositivo.
. Compruebe si el servicio FC o iSCSI está activo y en funcionamiento en el sistema de almacenamiento.
+
De lo contrario, póngase en contacto con el administrador de almacenamiento para conectar el sistema de almacenamiento.

. Compruebe si el servicio iSCSI o FC está activo en el host.


Si las soluciones anteriores no resuelven el problema, póngase en contacto con el soporte técnico.



| `0001-859` | NA | Admin | `None of the host's interfaces have NFS permissions to access directory <directory name> on storage system <storage system name>` | En la `snapdrive.conf` asegúrese de que `_check-export-permission-nfs-clone_` la variable de configuración se establece en `off`. 


| `0002-253` |  | Admin | `Flex clone creation failed` | Es un error del lado del sistema de almacenamiento. Recoja los registros del sd-trace.log y del sistema de almacenamiento para solucionar el problema. 


| `0002-264` |  | Admin | `FlexClone is not supported on filer <filer name>` | FlexClone no es compatible con la versión Data ONTAP actual del sistema de almacenamiento. Actualice la versión de Data ONTAP del sistema de almacenamiento a la versión 7.0 o posterior y vuelva a intentar el comando. 


| `0002-265` |  | Admin | `Unable to check flex_clone license on filer <filername>` | Es un error del lado del sistema de almacenamiento. Recopile los registros de sd-trace.log y del sistema de almacenamiento para solucionar problemas. 


| `0002-266` | NA | Admin | `FlexClone is not licensed on filer <filername>` | La licencia de FlexClone no está activada en el sistema de almacenamiento. Vuelva a intentar el comando después de agregar una licencia de FlexClone en el sistema de almacenamiento. 


| `0002-267` | NA | Admin | `FlexClone is not supported on root volume <volume-name>` | No se pueden crear FlexClones para volúmenes raíz. 


| `0002-270` | NA | Admin | `The free space on the aggregate <aggregate-name> is less than <size> MB(megabytes) required for diskgroup/flexclone metadata`  a| 
. El espacio mínimo requerido en el lvm nativo de AIX es aproximadamente 12.58 MB, mientras que otros requieren ~8.39 MB.
. Para la conexión a LUN sin configurar mediante FlexClone, se necesita 2 MB de espacio libre en el agregado.
. Libere espacio en el agregado de acuerdo con los pasos 1 y 2 y vuelva a intentar el comando.




| `0002-332` | NA | Admin | `SD.SnapShot.Restore access denied on qtree storage_array1:/vol/vol1/qtree1 for user lnx197-142\john` | Póngase en contacto con el administrador de Operations Manager para otorgar la capacidad necesaria al usuario. 


| `0002-364` | NA | Admin | `Unable to contact DFM: lnx197-146, please change user name and/or password.` | Verifique y corrija el nombre de usuario y la contraseña del usuario de sd-admin. 


| `0002-268` | NA | Admin | `<volume-Name> is not a flexible volume` | No se pueden crear FlexClones para los volúmenes tradicionales. 


| `0001-552` | NA | Comando | `Not a valid Volume-clone or LUN-clone` | La división de clones no se puede crear para los volúmenes tradicionales. 


| `0001-553` | NA | Comando | `Unable to split "`FS-Name`" due to insufficient storage space in <Filer- Name>` | La división de clones continúa el proceso de separación y, de repente, la división de clones se detiene debido a que no hay espacio de almacenamiento disponible en el sistema de almacenamiento. 


| `9000- 023` | 1 | Comando | `No arguments for keyword -lun`  a| 
Este error se produce cuando el comando con el `-lun` la palabra clave no tiene `_lun_name_` argumento.

Qué hacer: Hacer una de las siguientes acciones:

. Especifique el `lun_name` argumento para el comando con `-lun` palabra clave.
. Compruebe el mensaje de ayuda de SnapDrive for UNIX




| `0001-028` | 1 | Comando | `File system </mnt/qa/dg4/vol1> is of a type (hfs) not managed by snapdrive. Please resubmit your request, leaving out the file system <mnt/qa/dg4/vol1>`  a| 
Este error se produce cuando un tipo de sistema de archivos no compatible forma parte de un comando.

Qué hacer: Excluya o actualice el tipo de sistema de archivos y, a continuación, vuelva a utilizar el comando.

Para obtener la información de compatibilidad de software más reciente, consulte la matriz de interoperabilidad.



| `9000-030` | 1 | Comando | `-lun may not be combined with other keywords` | Este error se produce cuando se combina el `-lun` palabra clave con `-fs` o. `-dg` palabra clave. Este es un error de sintaxis e indica que el uso del comando no es válido. Qué hacer: Ejecute el comando de nuevo sólo con el `-lun` palabra clave. 


| `0001-034` | 1 | Comando | `mount failed: mount: <device name> is not a valid block device"`  a| 
Este error se produce únicamente cuando la LUN clonada ya está conectada con el mismo filespec. Presente en la copia Snapshot y después se intenta ejecutar el `snapdrive snap restore` comando.

Se produce un error en el comando porque el daemon iSCSI vuelve a asignar la entrada de dispositivo para la LUN restaurada cuando se elimina la LUN clonada.

Qué hacer: Realice una de las siguientes acciones:

. Ejecute el `snapdrive snap restore` comando de nuevo.
. Elimine la LUN conectada (si está montada en el mismo filespec. Que en la copia Snapshot) antes de intentar restaurar una copia Snapshot de una LUN original.




| `0001-046` y.. `0001-047` | 1 | Comando | `Invalid snapshot name: </vol/vol1/NO_FILER_PRE FIX> or Invalid snapshot name: NO_LONG_FILERNAME - filer volume name is missing`  a| 
Este es un error de sintaxis que indica que el uso del comando no es válido, donde se intenta una operación de Snapshot con un nombre de Snapshot no válido.

Qué hacer: Realice los siguientes pasos:

. Utilice el comando snap list - filer <filer-volume-name> de SnapDrive para obtener una lista de copias snapshot.
. Ejecute el comando con el argumento long_snap_name.




| `9000-047` | 1 | Comando | `More than one -snapname argument given` | SnapDrive para UNIX no puede aceptar más de un nombre de Snapshot en la línea de comandos para realizar cualquier operación de Snapshot. Qué hacer: Ejecute de nuevo el comando con un solo nombre de snapshot. 


| `9000-049` | 1 | Comando | `-dg and -vg may not be combined`  a| 
Este error se produce cuando se combina el `-dg` y.. `-vg` palabras clave. Este es un error de sintaxis e indica un uso no válido de los comandos.

Qué hacer: Ejecute el comando con el `-dg` o. `-vg` palabra clave.



| `9000-050` | 1 | Comando | `-lvol and -hostvol may not be combined`  a| 
Este error se produce cuando se combina el `-lvol` y.. `-hostvol` palabras clave. Este es un error de sintaxis e indica un uso no válido de los comandos. Qué hacer: Realice los siguientes pasos:

. Cambie el `-lvol` opción a. `- hostvol` o viceversa en la línea de comandos.
. Ejecute el comando.




| `9000-057` | 1 | Comando | `Missing required -snapname argument` | Se trata de un error de sintaxis que indica un uso no válido del comando, en el que se intenta realizar una operación Snapshot sin proporcionar el argumento snap_name. Qué se debe hacer: Ejecute el comando con un nombre de Snapshot adecuado. 


| `0001-067` | 6 | Comando | `Snapshot hourly.0 was not created by snapdrive.` | Estas son las copias automáticas cada hora que crea Data ONTAP. 


| `0001-092` | 6 | Comando | `snapshot <non_existent_24965> doesn't exist on a filervol exocet: </vol/vol1>` | No se encontró la copia Snapshot especificada en el sistema de almacenamiento. Qué hacer: Utilice `snapdrive snap list` Comando para encontrar las copias de Snapshot que existen en el sistema de almacenamiento. 


| `0001- 099` | 10 | Admin | `Invalid snapshot name: <exocet:/vol2/dbvol:New SnapName> doesn't match filer volume name <exocet:/vol/vol1>`  a| 
Este es un error de sintaxis que indica que el uso de comandos no es válido, donde se intenta una operación de Snapshot con un nombre de Snapshot no válido.

Qué hacer: Realice los siguientes pasos:

. Utilice la `snapdrive snap list - filer _<filer-volume-name>_` Comando para obtener una lista de copias Snapshot.
. Ejecute el comando con el formato correcto del nombre de snapshot cualificado por SnapDrive para UNIX. Los formatos admitidos son: `_long_snap_name_` y.. `_short_snap_name_`.




| `0001-122` | 6 | Admin | `Failed to get snapshot list on filer <exocet>: The specified volume does not exist.`  a| 
Este error se produce cuando no existe el volumen del sistema de almacenamiento (servidor de almacenamiento) especificado.

Qué hacer: Realice los siguientes pasos:

. Comuníquese con el administrador de almacenamiento para obtener la lista de volúmenes válidos del sistema de almacenamiento.
. Ejecute el comando con un nombre de volumen del sistema de almacenamiento válido.




| `0001-124` | 111 | Admin | `Failed to removesnapshot <snap_delete_multi_inuse_24374> on filer <exocet>: LUN clone`  a| 
La `Snapshot delete` Se ha producido un error en la operación para la copia Snapshot especificada porque estaba presente el clon de la LUN.

Qué hacer: Realice los siguientes pasos:

. Use el comando SnapDrive Storage show con el `-all` Opción para encontrar el clon de LUN para la copia Snapshot (parte del resultado de la copia Snapshot que se realiza el backup).
. Póngase en contacto con el administrador de almacenamiento para dividir la LUN del clon.
. Vuelva a ejecutar el comando.




| `0001-155` | 4 | Comando | `Snapshot <dup_snapname23980> already exists on <exocet: /vol/vol1>. Please use -f (force) flag to overwrite existing snapshot`  a| 
Este error se produce si el nombre de copia Snapshot que se utiliza en el comando ya existe.

Qué hacer: Realice una de las siguientes acciones:

. Ejecute el comando de nuevo con otro nombre de snapshot.
. Vuelva a ejecutar el comando con la `-f` (Forzar) para sobrescribir la copia Snapshot existente.




| `0001-158` | 84 | Comando | `diskgroup configuration has changed since <snapshotexocet:/vol/vo l1:overwrite_noforce_25 078> was taken. removed hostvol </dev/dg3/vol4> Please use '-f' (force) flag to override warning and complete restore`  a| 
El grupo de discos puede contener varias LUN y cuando se cambia la configuración del grupo de discos, se encuentra con este error. Por ejemplo, al crear una copia Snapshot, el grupo de discos consistía en X número de LUN y después de hacer la copia, el grupo de discos puede tener un número X+y de LUN.

Qué hacer: Utilice el comando de nuevo con el `-f` (fuerza).



| `0001-185` | NA | Comando | `storage show failed: no NETAPP devices to show or enable SSL on the filers or retry after changing snapdrive.conf to use http for filer communication.`  a| 
Este problema puede ocurrir por los siguientes motivos: Si el daemon iSCSI o el servicio de FC en el host se han detenido o no funciona, el `snapdrive storage show -all` Se produce un error en el comando, incluso si hay varios LUN configurados en el host.

Qué hacer: Resolver el servicio iSCSI o FC que no funciona correctamente.

El sistema de almacenamiento en el que se configuran las LUN está inactivo o está sometiendo a un reinicio.

Qué hacer: Espere hasta que estén up las LUN.

El valor establecido para `_usehttps- to-filer_` la variable de configuración puede no ser una configuración compatible.

Qué hacer: Realice los siguientes pasos:

. Utilice la `sanlun lun show all` Comando para comprobar si hay alguna LUN asignada al host.
. Si hay alguna LUN asignada al host, siga las instrucciones mencionadas en el mensaje de error.


Cambie el valor de `_usehttps- to-filer_` variable de configuración (a «'on'» si el valor es «'off'»; a «'off'' si el valor es «'on'»).



| `0001-226` | 3 | Comando | `'snap create' requires all filespecs to be accessible Please verify the following inaccessible filespec(s): File System: </mnt/qa/dg1/vol3>` | Este error se produce cuando la entidad del host especificada no existe. Qué hacer: Utilice `snapdrive storage show` de nuevo el comando con la `-all` opción para buscar las entidades host que existen en el host. 


| `0001- 242` | 18 | Admin | `Unable to connect to filer: <filername>`  a| 
SnapDrive para UNIX intenta conectarse a un sistema de almacenamiento a través del protocolo HTTP seguro. El error puede producirse cuando el host no se puede conectar con el sistema de almacenamiento. Qué hacer: Realice los siguientes pasos:

. Problemas de red:
+
.. Utilice el comando nslookup para comprobar la resolución de nombres DNS del sistema de almacenamiento que funciona a través del host.
.. Añada el sistema de almacenamiento al servidor DNS, si no existe.




También es posible usar una dirección IP en lugar de un nombre de host para conectarse al sistema de almacenamiento.

. Configuración del sistema de almacenamiento:
+
.. Para que SnapDrive para UNIX funcione, debe tener la clave de licencia para un acceso HTTP seguro.
.. Una vez configurada la clave de licencia, compruebe si el sistema de almacenamiento se puede acceder a través de un explorador web.


. Ejecute el comando después de realizar los pasos 1 o 2 o ambos.




| `0001- 243` | 10 | Comando | `Invalid dg name: <SDU_dg1>`  a| 
Este error se produce cuando el grupo de discos no está presente en el host y, posteriormente, se produce un error en el comando. Por ejemplo: `_SDU_dg1_` no está presente en el host.

Qué hacer: Realice los siguientes pasos:

. Utilice la `snapdrive storage show -all` comando para obtener todos los nombres del grupo de discos.
. Ejecute de nuevo el comando con el nombre correcto del grupo de discos.




| `0001- 246` | 10 | Comando | `Invalid hostvolume name: </mnt/qa/dg2/BADFS>, the valid format is <vgname/hostvolname>, i.e. <mygroup/vol2>` | Qué se deben hacer: Ejecute de nuevo el comando, con el siguiente formato adecuado para el nombre del volumen de host: `vgname/hostvolname` 


| `0001- 360` | 34 | Admin | `Failed to create LUN </vol/badvol1/nanehp13_ unnewDg_fve_SdLun> on filer <exocet>: No such volume` | Este error se produce cuando la ruta especificada incluye un volumen del sistema de almacenamiento que no existe. Qué hacer: Póngase en contacto con el administrador de almacenamiento para obtener la lista de los volúmenes del sistema de almacenamiento que están disponibles para su uso. 


| `0001- 372` | 58 | Comando | `Bad lun name::` `</vol/vol1/sce_lun2a> - format not recognized`  a| 
Este error se produce si los nombres de las LUN especificados en el comando no cumplen con el formato predefinido que admite SnapDrive para UNIX. SnapDrive para UNIX requiere que los nombres de las LUN se especifiquen en el siguiente formato predefinido: `<filer-name: /vol/<volname>/<lun-name>`

Qué hacer: Realice los siguientes pasos:

. Utilice la `snapdrive help` Comando para conocer el formato predefinido para los nombres de LUN que admite SnapDrive para UNIX.
. Vuelva a ejecutar el comando.




| `0001- 373` | 6 | Comando | `The following required 1 LUN(s) not found: exocet:</vol/vol1/NotARealLun>`  a| 
Este error se produce cuando no se encuentra el LUN especificado en el sistema de almacenamiento.

Qué hacer: Realice una de las siguientes acciones:

. Para ver los LUN conectados al host, utilice `snapdrive storage show -dev` command o. `snapdrive storage show -all` comando.
. Para ver toda la lista de LUN en el sistema de almacenamiento, póngase en contacto con el administrador de almacenamiento para obtener el resultado del comando lun show del sistema de almacenamiento.




| `0001- 377` | 43 | Comando | `Disk group name <name> is already in use or conflicts with another entity.`  a| 
Este error se produce cuando el nombre del grupo de discos ya está en uso o entra en conflicto con otra entidad. Qué hacer: Realice una de las siguientes acciones:

Ejecute el comando con la opción - autorename

Utilice la `snapdrive storage show` con el `-all` opción para buscar los nombres que usa el host. Ejecute el comando que especifica otro nombre que el host no está usando.



| `0001- 380` | 43 | Comando | `Host volume name <dg3/vol1> is already in use or conflicts with another entity.`  a| 
Este error se produce cuando el nombre del volumen de host ya está en uso o entra en conflicto con otra entidad

Qué hacer: Realice una de las siguientes acciones:

. Ejecute el comando con el `- autorename` opción.
. Utilice la `snapdrive storage show` con el `-all` opción para buscar los nombres que usa el host. Ejecute el comando que especifica otro nombre que el host no está usando.




| `0001- 417` | 51 | Comando | `The following names are already in use: <mydg1>. Please specify other names.`  a| 
Qué hacer: Realice una de las siguientes acciones:

. Vuelva a ejecutar el comando con la `-autorename` opción.
. Uso `snapdrive storage show - all` comando para encontrar los nombres que existen en el host. Ejecute de nuevo el comando para especificar explícitamente otro nombre que el host no está utilizando.




| `0001- 430` | 51 | Comando | `You cannot specify both -dg/vg dg and - lvol/hostvol dg/vol`  a| 
Este es un error de sintaxis que indica un uso no válido de los comandos. La línea de comandos puede aceptar cualquiera de los dos `-dg/vg` o la `-lvol/hostvol` palabra clave, pero no ambos.

Qué hacer: Ejecute el comando con solo la `-dg/vg` o. `- lvol/hostvol` palabra clave.



| `0001- 434` | 6 | Comando | `snapshot exocet:/vol/vol1:NOT_E IST doesn't exist on a storage volume exocet:/vol/vol1`  a| 
Este error se produce cuando no se encuentra la copia Snapshot especificada en el sistema de almacenamiento.

Qué hacer: Utilice `snapdrive snap list` Comando para encontrar las copias de Snapshot que existen en el sistema de almacenamiento.



| `0001- 435` | 3 | Comando | `You must specify all host volumes and/or all file systems on the command line or give the -autoexpand option. The following names were missing on the command line but were found in snapshot <snap2_5VG_SINGLELUN _REMOTE>: Host Volumes: <dg3/vol2> File Systems: </mnt/qa/dg3/vol2>`  a| 
El grupo de discos especificado tiene varios volúmenes host o sistema de archivos, pero el conjunto completo no se menciona en el comando.

Qué hacer: Realice una de las siguientes acciones:

. Vuelva a emitir el comando con el `- autoexpand` opción.
. Utilice la `snapdrive snap show` comando para encontrar la lista completa de volúmenes de host y sistemas de archivos. Ejecute el comando especificando todos los volúmenes host o los sistemas de archivos.




| `0001- 440` | 6 | Comando | `snapshot snap2__5VG_SINGLELUN__ REMOTE does not contain disk group 'dgBAD'`  a| 
Este error se produce cuando el grupo de discos especificado no forma parte de la copia Snapshot especificada.

Qué hacer: Para encontrar si hay alguna copia Snapshot para el grupo de discos especificado, realice una de las siguientes acciones:

. Utilice la `snapdrive snap list` Comando para encontrar las copias de Snapshot en el sistema de almacenamiento.
. Utilice la `snapdrive snap show` Comando para encontrar los grupos de discos, los volúmenes de host, los sistemas de archivos o los LUN presentes en la copia Snapshot.
. Si existe una copia Snapshot para el grupo de discos, ejecute el comando con el nombre Snapshot.




| `0001- 442` | 1 | Comando | `More than one destination - <dis> and <dis1> specified for a single snap connect source <src>. Please retry using separate commands.` | Qué hacer: Ejecutar un separado `snapdrive snap connect` de modo que el nuevo nombre del grupo de discos de destino (que forma parte del comando snap connect) no sea igual que lo que ya forma parte de las demás unidades de grupo de discos de la misma `snapdrive snap connect` comando. 


| `0001- 465` | 1 | Comando | `The following filespecs do not exist and cannot be deleted: Disk Group: <nanehp13_ dg1>` | El grupo de discos especificado no existe en el host, por lo tanto, ha fallado la operación de eliminación del grupo de discos especificado. Qué hacer: Consulte la lista de entidades del host mediante el `snapdrive storage show` con el `all` opción. 


| `0001- 476` | NA | Admin | `Unable to discover the device associated with <long lun name> If multipathing in use, there may be a possible multipathing configuration error. Please verify the configuration and then retry.`  a| 
Puede haber muchas razones para este fracaso.

* Configuración de host no válida:
+
La solución iSCSI, FC o multivía no se ha configurado correctamente.

* Configuración de switch o red no válida:
+
La red IP no se configura con las reglas de reenvío o los filtros adecuados para el tráfico iSCSI; de lo contrario, los switches FC no están configurados con la configuración de zonas recomendada.



Los problemas anteriores son muy difíciles de diagnosticar de una manera algorítmica o secuencial.

Qué hacer: NetAppIT recomienda que antes de utilizar SnapDrive para UNIX, siga los pasos recomendados en la Guía de configuración de utilidades de host (para el sistema operativo específico) para detectar las LUN manualmente.

Después de detectar las LUN, utilice los comandos de la SnapDrive para UNIX.



| `0001- 486` | 12 | Admin | `LUN(s) in use, unable to delete. Please note it is dangerous to remove LUNs that are under Volume Manager control without properly removing them from Volume Manager control first.`  a| 
SnapDrive para UNIX no puede eliminar una LUN que forme parte de un grupo de volúmenes.

Qué hacer: Realice los siguientes pasos:

. Elimine el grupo de discos con el comando `snapdrive storage delete -dg _<dgname>_`.
. Elimine la LUN.




| `0001- 494` | 12 | Comando | `Snapdrive cannot delete <mydg1>, because 1 host volumes still remain on it. Use -full flag to delete all file systems and host volumes associated with <mydg1>`  a| 
SnapDrive para UNIX no puede eliminar un grupo de discos hasta que se soliciten explícitamente la eliminación de todos los volúmenes host en el grupo de discos.

Qué hacer: Realice una de las siguientes acciones:

. Especifique el `-full` indicador en el comando.
. Complete los siguientes pasos:
+
.. Utilice la `snapdrive storage show -all` comando para obtener la lista de los volúmenes de host que están en el grupo de discos.
.. Mencione de forma explícita cada una de ellas en el comando SnapDrive for UNIX.






| `0001- 541` | 65 | Comando | `Insufficient access permission to create a LUN on filer, <exocet>.`  a| 
SnapDrive para UNIX utiliza `sdhostname.prbac` o. `sdgeneric.prbacfile` en el volumen del sistema de almacenamiento raíz (filer) para su pcc de control de acceso.

Qué hacer: Realice una de las siguientes acciones:

. Modifique el `sd-hostname.prbac` o. `sdgeneric. prbac` de almacenamiento a fin de incluir los siguientes permisos necesarios (pueden ser uno o varios):
+
.. NINGUNO
.. CREAR SNAP
.. SNAP USE
.. ENGANCHE TODO
.. ALMACENAMIENTO CREAR ELIMINACIÓN
.. EL USO DEL ALMACENAMIENTO
.. ALMACENAMIENTO TODO
.. TODOS LOS ACCESOS




*NOTA:*

* Si no tiene `sd-hostname.prbac` a continuación, modifique el `sdgeneric.prbac` archivo en el sistema de almacenamiento.
* Si usted tiene ambos `sd-hostname.prbac` y.. `sdgeneric.prbac` a continuación, modifique la configuración sólo en `sdhostname.prbac` archivo en el sistema de almacenamiento.
+
.. En la `snapdrive.conf` asegúrese de que `_all-access-if-rbacunspecified_` la variable de configuración se establece en "'on'".






| `0001-559` | NA | Admin | `Detected I/Os while taking snapshot. Please quiesce your application. See Snapdrive Admin. Guide for more information.` | Este error se produce si intenta crear una copia snapshot, mientras que las operaciones de entrada/salida paralelas se producen en la especificación de archivo y el valor de `_snapcreate-cg-timeout_` está configurado como urgente. Qué hacer: Aumente el valor de los grupos de consistencia tiempo de espera mediante la configuración del valor de `_snapcreate-cg-timeout_` para relajarse. 


| `0001- 570` | 6 | Comando | `Disk group <dg1> does not exist and hence cannot be resized`  a| 
Este error se produce cuando el grupo de discos no está presente en el host y, posteriormente, se produce un error en el comando.

Qué hacer: Realice los siguientes pasos:

. Utilice la `snapdrive storage show -all` comando para obtener todos los nombres del grupo de discos.
. Ejecute el comando con el nombre correcto del grupo de discos.




| `0001- 574` | 1 | Comando | `<VmAssistant> lvm does not support resizing LUNs in disk groups`  a| 
Este error se produce cuando el administrador de volúmenes que se usa para realizar esta tarea no admite el cambio de tamaño de LUN.

SnapDrive para UNIX depende de la solución de gestor de volúmenes para admitir el cambio de tamaño de la LUN, si la LUN forma parte de un grupo de discos.

Qué hacer: Compruebe si el administrador de volúmenes que utiliza admite el cambio de tamaño de LUN.



| `0001- 616` | 6 | Comando | `1 snapshot(s) NOT found on filer: exocet:/vol/vol1:MySnapName>`  a| 
SnapDrive para UNIX no puede aceptar más de un nombre de Snapshot en la línea de comandos para realizar cualquier operación de Snapshot. Para corregir este error, vuelva a emitir el comando con un nombre de snapshot.

Este es un error de sintaxis que indica que el uso del comando no es válido, donde se intenta una operación de Snapshot con un nombre de Snapshot no válido. Para rectificar este error, lleve a cabo los siguientes pasos:

. Utilice la `snapdrive snap list - filer <filer-volume-name>` Comando para obtener una lista de copias Snapshot.
. Ejecute el comando con el `_long_snap_name_` argumento.




| `0001- 640` | 1 | Comando | `Root file system / is not managed by snapdrive` | Este error se produce cuando SnapDrive para UNIX no admite el sistema de archivos raíz del host. Esta es una solicitud no válida para SnapDrive para UNIX. 


| `0001- 684` | 45 | Admin | `Mount point <fs_spec> already exists in mount table`  a| 
Qué hacer: Realice una de las siguientes acciones:

. Ejecute el comando SnapDrive para UNIX con un punto de montaje diferente.
. Compruebe que el punto de montaje no está en uso y, a continuación, elimine manualmente (mediante cualquier editor) la entrada de los siguientes archivos:


AIX: /Etc/filesystems



| `0001- 796 and 0001- 767` | 3 | Comando | `0001-796 and 0001-767`  a| 
SnapDrive para UNIX no admite más de una LUN en el mismo comando con el `-nolvm` opción.

Qué hacer: Realice una de las siguientes acciones:

. Utilice el comando de nuevo para especificar solo una LUN con el `-nolvm` opción.
. Utilice el comando sin el `- nolvm` opción. Esto usará el administrador de volúmenes admitido presente en el host, si lo hubiera.




| `2715` | NA | NA | `Volume restore zephyr not available for the filer <filename>Please proceed with lun restore` | No está disponible la zapi de restauración de volúmenes para versiones anteriores de Data ONTAP. Vuelva a emitir el comando con SFSR. 


| `2278` | NA | NA | `SnapShots created after <snapname> do not have volume clones ... FAILED` | Divida o elimine los clones 


| `2280` | NA | NA | `LUNs mapped and not in active or SnapShot <filespec-name> FAILED` | Desasignar/almacenar desconecte las entidades host 


| `2282` | NA | NA | `No SnapMirror relationships exist ... FAILED`  a| 
. Elimine las relaciones o.
. Si está configurado el control de acceso basado en roles de SnapDrive para UNIX con Operations Manager, pida al administrador de Operations Manager que lo conceda `SD.Snapshot.DisruptBaseline` capacidad para el usuario.




| `2286` | NA | NA | `LUNs not owned by <fsname> are application consistent in snapshotted volume ... FAILED. Snapshot luns not owned by <fsname> which may be application inconsistent` | Compruebe que las LUN mencionadas en los resultados de la comprobación no están en uso. Sólo después de eso, utilice la `-force` opción. 


| `2289` | NA | NA | `No new LUNs created after snapshot <snapname> ... FAILED` | Compruebe que las LUN mencionadas en los resultados de la comprobación no están en uso. Sólo después de eso, utilice la `-force` opción. 


| `2290` | NA | NA | `Could not perform inconsistent and newer Luns check. Snapshot version is prior to SDU 4.0` | Esto sucede con SnapDrive 3.0 para instantáneas UNIX cuando se utiliza con `-vbsr`. Compruebe manualmente que las nuevas LUN creadas ya no se utilizarán y continúe con `-force` opción. 


| `2292` | NA | NA | `No new SnapShots exist... FAILED. SnapShots created will be lost.` | Compruebe que las instantáneas mencionadas en los resultados de comprobación ya no se utilizarán. Y si es así, continúe con `-force` opción. 


| `2297` | NA | NA | `Both normal files) and LUN(s) exist ... FAILED` | Asegúrese de que los archivos y las LUN mencionados en los resultados de la comprobación ya no se utilizarán. Y si es así, continúe con `-force` opción. 


| `2302` | NA | NA | `NFS export list does not have foreign hosts ... FAILED` | Póngase en contacto con el administrador de almacenamiento para quitar los hosts externos de la lista de exportación o asegúrese de que los hosts externos no usen los volúmenes a través de NFS. 


| `9000-305` | NA | Comando | `Could not detect type of the entity /mnt/my_fs. Provide a specific option (-lun, -dg, -fs or -lvol) if you know the type of the entity` | Verifique la entidad si ya existe en el host. Si conoce el tipo de entidad, proporcione el tipo de especificación de archivo. 


| `9000-303` | NA | Comando | `Multiple entities with the same name - /mnt/my_fs exist on this host. Provide a specific option (-lun, -dg, -fs or -lvol) for the entity you have specified.` | El usuario tiene varias entidades con el mismo nombre. En este caso, el usuario debe proporcionar explícitamente el tipo de especificación de archivo. 


| `9000-304` | NA | Comando | `/mnt/my_fs is detected as keyword of type file system, which is not supported with this command.` | El funcionamiento en el archivo auto detectado File_spec no es compatible con este comando. Verifique con la ayuda correspondiente para la operación. 


| `9000-301` | NA | Comando | `Internal error in auto defection` | Error del motor de detección automática. Proporcione la traza y el registro del daemon para su posterior análisis. 


| NA | NA | Comando | `snapdrive.dc tool unable to compress data on RHEL 5Ux environment`  a| 
La utilidad de compresión no está instalada de forma predeterminada. Debe instalar la utilidad de compresión `ncompress`, por ejemplo `ncompress-4.2.4-47.i386.rpm`.

Para instalar la utilidad de compresión, introduzca el siguiente comando: Rpm -ivh ncompress-4.2.4-47.i386.rpm



| NA | NA | Comando | `Invalid filespec` | Este error se produce cuando la entidad host especificada no existe ni se puede acceder a ella. 


| NA | NA | Comando | `Job Id is not valid` | Este mensaje se muestra para el estado de división de clones, el resultado o la operación de detención si el ID de trabajo especificado no es un trabajo válido o el resultado del trabajo ya se consulta. Debe especificar un ID de trabajo válido o disponible y volver a intentar esta operación. 


| NA | NA | Comando | `Split is already in progress`  a| 
Este mensaje aparece cuando:

* La división de clones ya está en curso en el clon de volumen o de LUN indicado.
* La división de clones se ha completado, pero el trabajo no se ha eliminado.




| NA | NA | Comando | `Not a valid Volume-Clone or LUN-Clone` | El nombre de ruta especificado filespec o LUN no es un clon de volumen o LUN válido. 


| NA | NA | Comando | `No space to split volume`  a| 
El mensaje de error se debe a que el espacio de almacenamiento necesario no está disponible para dividir el volumen. Libere espacio suficiente en el agregado para dividir el clon del volumen.



| NA | NA | NA | `filer-data:junction_dbsw information not available -- LUN may be offline`  a| 
Este error podría ocurrir cuando el `/etc/fstab` el archivo se ha configurado incorrectamente. En este caso, mientras que las rutas de montaje eran NFS, pero se consideraban LUN de SnapDrive para UNIX.

Qué hacer: Agregue "/" entre el nombre del archivador y la ruta de unión.



| `0003-013` | NA | Comando | `A connection error occurred with Virtual Interface server. Please check if Virtual Interface server is up and running.`  a| 
Este error puede ocurrir cuando caduca la licencia del servidor esx y el servicio VSC no está en ejecución.

Qué hacer: Instalar la licencia de ESX Server y reiniciar el servicio VSC.



| `0002-137` | NA | Comando | `Unable to get the fstype and mntOpts for 10.231.72.21:/vol/ips_vol3 from snapshot 10.231.72.21:/vol/ips_vol3:t5120-206-66_nfssnap.`  a| 
Qué hacer: Realice una de las siguientes acciones

. Agregue la dirección IP de la interfaz de ruta de datos o la dirección IP específica como nombre de host en el `/etc/hosts` archivo.
. Cree una entrada para la interfaz de ruta de datos o la dirección IP del nombre de host en el DNS.
. Configurar las LIF de datos de Vserver para admitir la gestión de Vserver (con firewall-policy=mgmt)
+
`*net int modify -vserver _Vserver_name LIF_name-firewall-policy_ mgmt*`

. Añada la dirección IP de administración del host a las reglas de exportación del Vserver.




| `13003` | NA | Comando | `Insufficient privileges: user does not have read access to this resource.`  a| 
Este problema se puede ver en SnapDrive para UNIX 5.2.2. Antes de trabajar con SnapDrive para UNIX 5.2.2, el usuario vsadmin configurado en SnapDrive para UNIX necesita tener el rol 'vsadmin_volume'. Desde SnapDrive para UNIX 5.2.2, el usuario de vsadmin necesita tener roles de acceso elevados; de lo contrario, se producirá un error en zapi de snapmirror-get-iter.

Qué hacer: Crear el rol vsadmin en lugar de vsadmin_volume y asignar al usuario vsadmin.



| `0001-016` | NA | Comando | `Could not acquire lock file on storage system.`  a| 
Error en la creación de la snapshot debido a la falta de espacio en el volumen. O debido a la existencia de `.snapdrive_lock` archivo en el sistema de almacenamiento.

Qué hacer: Realice una de las siguientes acciones:

. Eliminar archivo `/vol/<volname>/.snapdrive_lock` en el sistema de almacenamiento y vuelva a intentar la operación de creación de snap. Para eliminar el archivo, inicie sesión en el sistema de almacenamiento, introduzca el modo de privilegio avanzado y ejecute el comando `rm /vol/<volname>/.snapdrive_lock` en el aviso del sistema de almacenamiento.
. Asegúrese de que haya suficiente espacio disponible en el volumen antes de realizar la snapshot.




| `0003-003` | NA | Admin | `Failed to export LUN on storage system <controller name> to the Guest OS. Reason: FLOW-11019: Failure in MapStorage: No storage system configured with interface.`  a| 
Este error se produce debido a la ausencia de controladoras de almacenamiento, que se configuran en el servidor ESX.

Qué hacer: Añada las controladoras de almacenamiento y las credenciales en el servidor ESX.



| `0001-493` | NA | Admin | `Error creating mount point: Unexpected error from mkdir: mkdir: cannot create directory: Permission denied Check whether mount point is under automount paths.`  a| 
Se produce un error en las operaciones de clonado cuando la especificación del archivo de destino se encuentra en las rutas de autoacceso.

Qué hacer: Asegurarse de que el punto de montaje/filespec de destino no esté bajo las rutas de montaje automático.



| `0009-049` | NA | Admin | `Failed to restore from snapshot on storage system: Failed to restore file from Snapshot copy for volume on Vserver.`  a| 
Este error se produce cuando el tamaño del volumen está completo o si el volumen superó el umbral de eliminación automática.

Qué hacer: Aumente el tamaño del volumen y asegúrese de que el valor del umbral de un volumen se mantenga por debajo del valor de eliminación automática.



| `0001-682` | NA | Admin | `Host preparation for new LUNs failed: This functionality is not supported.`  a| 
Este error se produce cuando se produce un error al crear los nuevos ID de LUN.

Qué hacer: Aumente el número de LUN que se van a crear con

`*snapdrive config prepare luns-_count count_value_*`

comando.



| `0001-060` | NA | Admin | `Failed to get information about Diskgroup: Volume Manager linuxlvm returned vgdisplay command failed.`  a| 
Este error ocurre cuando se utiliza SnapDrive para UNIX 4.1.1 y una versión inferior en RHEL 5 y versiones posteriores.

Qué hacer: Actualizar la versión de SnapDrive y volver a intentarlo, ya que no hay compatibilidad con SnapDrive para UNIX 4.1.1 y versiones anteriores a partir de RHEL5.



| `0009-045` | NA | Admin | `Failed to create snapshot on storage system: Snapshot operation not allowed due to clones backed by snapshots. Try again after sometime.`  a| 
Este error se produce durante la operación Single File Snap Restore (SFSR) seguida de la creación inmediata de una snapshot.

Qué se debe hacer: Vuelva a intentar la operación de creación de Snapshot después de algún momento.



| `0001-304` | NA | Admin | `Error creating disk/volume group: Volume manager failed with: metainit: No such file or directory.`  a| 
Este error se produce mientras se realiza SnapDrive Storage create dg, hostvol y fs Solaris con el entorno Sun Cluster.

Qué hacer: Desinstale el software Sun Cluster y vuelva a intentar las operaciones.



| `0001-122` | NA | Admin | `Failed to get snapshot list on filer the specified volume <volname> does not exist.`  a| 
Este error se produce cuando SnapDrive para UNIX intenta crear Snapshot utilizando la ruta de acceso del sistema de archivos activos exportada del volumen (ruta real) y no con la ruta de acceso del volumen exportada simulada.

Qué hacer: Se utilizan volúmenes con la ruta de acceso del sistema de archivos activo exportada.



| `0001-476` | NA | Admin | `Unable to discover the device. If multipathing in use, there may be a possible multipathing configuration error. Please verify the configuration and then retry.`  a| 
Existen varias razones para que se produzca este error.

Deben comprobarse las siguientes condiciones: Antes de crear el almacenamiento, asegúrese de que la división en zonas sea adecuada.

Compruebe el protocolo de transporte y el tipo multivía `snapdrive.conf` archivo y asegúrese de que se han establecido los valores adecuados.

Compruebe el estado del daemon multipath si el tipo de acceso múltiple está establecido como nativempio start multipathd y reinicie el daemon snapdrived.



| NA | NA | NA | `FS fails to be mounted after reboot due to unavailability of LV.`  a| 
Esto sucede cuando el VI no está disponible después del reinicio. Por lo tanto, el sistema de archivos no está montado.

Qué hacer: Después del reinicio, haga vgchange que trae LV hacia arriba y luego monte el sistema de archivos.



| NA | NA | NA | `Status call to SDU daemon failed.`  a| 
Hay varios motivos para que se produzca este error. Este error indica que el trabajo de SnapDrive para UNIX relacionado con una operación específica ha fallado abruptamente (el demonio secundario ha finalizado) antes de que se pueda completar la operación.

Si se produce un error en la creación del almacenamiento o en la eliminación con "llamada de estado al demonio de SnapDrive para UNIX", podría deberse a que no pudiera llamar a ONTAP para obtener la información del volumen. podría fallar el zapi volume-get-iter. Vuelva a intentar las operaciones de SnapDrive después de algún tiempo.

El funcionamiento de SnapDrive para UNIX podría fallar mientras se ejecuta "kpartx -l" mientras se crean particiones u otros comandos del sistema operativo debido a que no es apropiado `multipath.conf` valores. Asegúrese de que se han establecido los valores adecuados y de que no existen palabras clave duplicadas en `multipath.conf` archivo.

Mientras se realiza SFSR, SnapDrive para UNIX crea una snapshot temporal que puede fallar si se ha alcanzado el número máximo de snapshots. Elimine las Snapshot más antiguas y vuelva a intentar la operación de restauración.



| NA | NA | NA | `map in use; can't flush`  a| 
Este error se produce si quedan dispositivos obsoletos al intentar vaciar el dispositivo multivía durante las operaciones de eliminación o desconexión de almacenamiento.

Qué hacer: Compruebe si hay dispositivos obsoletos ejecutando el comando

`*multipath*`

`_-l egrep -ifail_` y asegúrese `_flush_on_last_del_` está definido en 'sí' en la `multipath.conf` archivo.

|===
*Información relacionada*

https://mysupport.netapp.com/NOW/products/interoperability["Interoperabilidad de NetApp"]

https://library.netapp.com/ecm/ecm_download_file/ECMP1119223["Guía de instalación y configuración de AIX Host Utilities 6.0"]
