---
permalink: aix/task_configuring_user_credentials_on_snapdrive_for_unix.html 
sidebar: sidebar 
keywords: snap, snapdrive, user, credentials, operations, manager, console, configure 
summary: El administrador de SnapDrive para UNIX recibe credenciales de usuario del administrador de la consola de Operations Manager. Estas credenciales de usuario deben configurarse en SnapDrive para UNIX con el fin de que las operaciones de almacenamiento sean correctas. 
---
= Configurar las credenciales de usuario en SnapDrive para UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El administrador de SnapDrive para UNIX recibe credenciales de usuario del administrador de la consola de Operations Manager. Estas credenciales de usuario deben configurarse en SnapDrive para UNIX con el fin de que las operaciones de almacenamiento sean correctas.

.Pasos
. Configurar sd-admin en el sistema de almacenamiento.
+
[listing]
----
[root]#snapdrive config set -dfm sd-admin ops_mngr_server
Password for sd-admin:
Retype password:
----
. Configuración de sd-hostname en el sistema de almacenamiento.
+
[listing]
----
[root]#snapdrive config set sd-unix_host storage_array1
Password for sd-unix_host:
Retype password:
----
. Compruebe los pasos 1 y 2 utilizando `snapdrive config list` comando.
+
[listing]
----
user name       appliance name          appliance type
----------------------------------------------------
sd-admin        ops_mngr_server         DFM
sd-unix_host    storage_array1          StorageSystem
----
. Configure SnapDrive para UNIX para utilizar el control de acceso basado en roles (RBAC) de Operations Manager Console configurando la variable de configuración `rbac-method="dfm"` en la `snapdrive.conf` archivo.
+

NOTE: Las credenciales de usuario se cifran y guardan en el existente `.sdupw` archivo. La ubicación predeterminada del archivo anterior es `/opt/NetApp/snapdrive/.sdupw`.


