---
permalink: aix/task_enabling_multipathing.html 
sidebar: sidebar 
keywords: snap, snapdrive, enable, multipathing, hba 
summary: Para utilizar la multivía en SnapDrive para UNIX, debe completar los pasos que incluyen la instalación e inicio de HBA. Si utiliza una solución multivía que no sea de NetApp, debe descargar el software y el paquete de aplicaciones del sitio web del proveedor de HBA. 
---
= Habilitando el acceso multivía
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para utilizar la multivía en SnapDrive para UNIX, debe completar los pasos que incluyen la instalación e inicio de HBA. Si utiliza una solución multivía que no es de NetApp, debe descargar el software y el paquete de aplicaciones del sitio web del proveedor de HBA.

El sistema debe ejecutar versiones actuales de los componentes del sistema FC e iSCSI.

http://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"]

.Pasos
. Instale los HBA admitidos antes de instalar el software de utilidades de host adecuado.
+

NOTE: SnapDrive para UNIX admite HBA de varios proveedores.

. Inicie el servicio HBA.
+
Si el servicio HBA no está en ejecución, se muestra el siguiente mensaje de error cuando se ejecutan comandos de SnapDrive para UNIX, como `snapdrive storage create` y.. `snapdrive config prepare luns`:

+
[listing]
----
0001-876 Admin error: HBA assistant not found
----
+
Debe comprobar que la cantidad necesaria de rutas está en funcionamiento y en funcionamiento. Puede verificar las rutas mediante la utilidad sanlun, que se incluye con el software Host Utilities. Por ejemplo, en la configuración multivía de FC, puede utilizar el `sanlun fcp show adapter -v` comando.

+
En el siguiente ejemplo, hay dos puertos HBA (fcd0 y fcd1) conectados al host que están operativos (estado del puerto). Solo puede tener un HBA o iSCSI iniciador y debe configurar la multivía proporcionando más de una ruta a las LUN de destino.

+
[listing]
----
# sanlun fcp show adapter -v
adapter name: fcd0
WWPN: 50060b000038c428
WWNN: 50060b000038c429
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 1 of 2
port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd0
adapter name: fcd1
WWPN: 50060b000038c42a
WWNN: 50060b000038c42b
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 2 of 2 port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd1
----
+
Si la función multivía está habilitada en un host, hay varias rutas visibles para el mismo LUN. Puede utilizar el `sanlun lun show all` comando para comprobar las rutas. En el ejemplo siguiente, puede encontrar varias rutas a la misma LUN (`fish: /vol/vol1/lun`):

+
[listing]
----
filer:         lun-pathname        device filename  adapter    protocol   lun size              lun state
    filer_1:        fish/vol/vol1/l1      hdisk36          fcs0       FCP       5m   (5242880)        GOOD
    filer_2:        fish/vol/vol0/lunKr   hdisk39          fcs0       FCP       100m (104857600)      GOOD
    filer_3:        fish/vol/vol0/testaix hdisk2           fcs0       FCP       200m (209715200)      GOOD
    filer_4:        fish/vol/vol1/l1      hdisk45          fcs1       FCP       5m   (5242880)        GOOD
----
. En una configuración FC, dividir en zonas los puertos HBA del host y los puertos de destino mediante la configuración de la división en zonas del switch.
. Instalar y configurar el switch FC o iSCSI adecuado.
. Comprobar los requisitos de la pila de SnapDrive para UNIX.
. Instalar o actualizar SnapDrive para UNIX.
. Comprobar la instalación de SnapDrive para UNIX.
. Localice el `snapdrive.conf` ruta del archivo.
. Configure las siguientes variables de configuración en el `snapdrive.conf` archivo:
+
** `_multipathing-type_`
** `_default-transport_`
** `_fstype_`
** `_vmtype_`
+
Para cada host, el tipo multivía, el tipo de transporte, el sistema de archivos y el tipo de gestor de volúmenes dependen unos de otros. La siguiente tabla describe todas las combinaciones posibles:



+
|===
| Plataforma host | Tipo de transporte predeterminado | Tipo de acceso múltiple | tipo fstype | vmtype 


 a| 
AIX
 a| 
FCP
 a| 
absoluto
 a| 
jfs2 o jfs
 a| 
lvm



 a| 
nativempio
 a| 
jfs2 o jfs
 a| 
lvm



 a| 
dmp
 a| 
vxfs
 a| 
vxvm

|===
+
La tabla anterior muestra los valores admitidos de `_multipathing-type_`, `_default-transport_`, `_fstype_`, y. `_vmtype_` variables de configuración.

. Guarde la `snapdrive.conf` archivo.
+
SnapDrive para UNIX comprueba automáticamente este archivo cada vez que se inicia. Debe reiniciar el daemon SnapDrive para UNIX para que los cambios surtan efecto.



*Información relacionada*

http://mysupport.netapp.com["Soporte de NetApp"]

https://mysupport.netapp.com/NOW/products/interoperability["Interoperabilidad de NetApp"]

https://library.netapp.com/ecm/ecm_download_file/ECMP1119223["Guía de instalación y configuración de AIX Host Utilities 6.0"]
