---
permalink: aix/task_connecting_to_asnapshot_copy_thatcontains_luns.html 
sidebar: sidebar 
keywords: snap, snapdrive, lun, snapshot, copy, connect 
summary: Puede conectarse a una copia snapshot que contenga LUN mediante el comando SnapDrive snap connect. 
---
= Conectarse a una copia Snapshot que contiene LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede conectarse a una copia Snapshot que contiene LUN mediante el `snapdrive snap connect` comando.

.Pasos
. Introduzca la siguiente sintaxis de comando para conectarse a una copia Snapshot que contiene las LUN:
+
`*snapdrive snap connect -lun _s_lun_name d_lun_name_ [[-lun] _s_lun_name d_lun_name_... -snapname _long_snap_name_ [-igroup _ig_name_ [_ig_name_...]] [-split]*`

+

NOTE: Los _s_lun_name_ y _d_lun_name_ deberían tener el formato lun_name o Qtree_name/lun_name.



SnapDrive para UNIX clona las LUN que especifique y las conecta a una nueva ubicación.

El siguiente ejemplo conecta la LUN mylun1, en hornet/vol/vol1/tuesdaysnapshot a mylun1copy:

[listing]
----
# ./snapdrive snap connect -lun mylun1 mylun1copy -snapname
hornet:/vol/vol1:tuesdaysnapshot
connecting hornet:/vol/vol1/mylun1:
LUN copy mylun1copy ... created
(original: hornet:/vol/vol1/mylun1) mapping new lun(s) ... done
discovering new lun(s) ... done
----
El ejemplo siguiente conecta dos LUN, mylun1 y mylun2, a mylun1copy y mylun2copy, respectivamente:

[listing]
----
# ./snapdrive snap connect -lun mylun1 mylun1copy -lun mylun2
mylun2copy -snapname hornet:/vol/vol1:tuesdaysnapshot
connecting hornet:/vol/vol1/mylun1:
LUN copy mylun1copy ... created
(original: hornet:/vol/vol1/mylun1)
mapping new lun(s) ... done
connecting hornet:/vol/vol1/mylun2:
LUN copy mylun2copy ... created
(original: hornet:/vol/vol1/mylun2)
mapping new lun(s) ... done
discovering new lun(s) ... done
----