---
permalink: solaris/concept_guidelines_for_thestorage_connectcommand.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, connect, command 
summary: Debe seguir algunas directrices para utilizar el comando SnapDrive Storage connect. 
---
= Directrices para el comando Storage connect
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe seguir algunas directrices para utilizar el `snapdrive storage connect` comando.

El almacenamiento que incluye entidades de LVM tiene requisitos especiales. Para utilizar la `snapdrive storage connect` Para conectar entidades de LVM, tiene que crear el almacenamiento de modo que cada entidad de la jerarquía del almacenamiento tenga exactamente una instancia de la siguiente entidad. Por ejemplo, puede usar el `snapdrive storage connect` comando para conectar una jerarquía de almacenamiento que tenga un grupo de discos (dg1) con un volumen de host (hostvol1) y un sistema de archivos (fs1). Sin embargo, no puede utilizar la `snapdrive storage connect` comando para conectar una jerarquía que tiene un grupo de discos (dg1) con dos volúmenes host (hostvol1 y hostvol2) y dos sistemas de archivos (fs1 y fs2).
