---
permalink: solaris/concept_thin_provisioning_in_snapdrive_for_unix.html 
sidebar: sidebar 
keywords: snap, snapdrive, thin, provisioning 
summary: La función de thin provisioning de SnapDrive para UNIX permite al usuario tener más espacio de almacenamiento para los hosts del que realmente está disponible en el sistema de almacenamiento. 
---
= Thin provisioning en SnapDrive para UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La función de thin provisioning de SnapDrive para UNIX permite al usuario tener más espacio de almacenamiento para los hosts del que realmente está disponible en el sistema de almacenamiento.

Dentro de SnapDrive para UNIX, no se puede establecer el valor de reserva fraccionaria y no hay integración con funciones de Data ONTAP como la eliminación automática y el ajuste de tamaño automático. Estas funciones de Data ONTAP se pueden utilizar de forma segura con SnapDrive para UNIX; sin embargo, no hay conocimiento de SnapDrive para UNIX, si se produce un evento de eliminación automática o autotamaño.

*Información relacionada*

https://www.netapp.com/pdf.html?item=/media/19670-tr-3483.pdf["Informe técnico de NetApp 3483: Thin Provisioning en un entorno empresarial SAN o SAN IP DE NetApp"^]
