---
permalink: solaris/concept_manual_pages_installed_by_snapdrive_for_unix.html 
sidebar: sidebar 
keywords: snap, snapdrive, man, page, install 
summary: SnapDrive para UNIX proporciona páginas de manual en varios formatos. 
---
= Páginas de manual instaladas por SnapDrive para UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive para UNIX proporciona páginas de manual en varios formatos.

Las páginas de manual están disponibles en la siguiente ubicación:

* `/opt/NTAPsnapdrive/docs/snapdrive.1`
* `/opt/NTAPsnapdrive/docs/snapdrived.1`
* `/opt/NTAPsnapdrive/docs/snapdrive.1.html`
* `/opt/NTAPsnapdrive/docs/snapdrived.1.html`
* `/opt/NTAPsnapdrive/docs/solaris_info.1`
* `/opt/NTAPsnapdrive/docs/brocade_info.1`
* `/opt/NTAPsnapdrive/docs/mcdata_info.1`
* `/opt/NTAPsnapdrive/docs/cisco_info.1`
* `/opt/NTAPsnapdrive/docs/filer_info.1`
* `/opt/NTAPsnapdrive/docs/snapdrive.dc.1`


Si instala SnapDrive para UNIX en una zona raíz dispersa, no agregará páginas de manual en `/usr/share/man/` porque `/usr/share/man/` se monta como un sistema de archivos de solo lectura. Para extraer las páginas man de una zona root dispersa, ejecute el `pkgtrans NTAPsnapdrive.pkg /tmp` comando. Después de ejecutar el comando, se extraen las páginas de manual a. `/tmp/NTAPsnapdrive/root/opt/NTAPsnapdrive/docs` .
