---
permalink: solaris/reference_storage_provisioning_command_lines.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, command, line, provisioning 
summary: Algunos comandos de SnapDrive para UNIX se usan para el aprovisionamiento de almacenamiento. 
---
= Líneas de comandos de aprovisionamiento de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Algunos comandos de SnapDrive para UNIX se usan para el aprovisionamiento de almacenamiento.

Las siguientes opciones de línea de comandos se utilizan para las operaciones de aprovisionamiento del almacenamiento:

|===
| Funcionamiento | Opción de línea de comandos 


 a| 
Cree
 a| 
`snapdrive storage create-lun _long_lun_name_ [_lun_name ..._] -lunsize _size_ [{ -dg | -vg } _dg_name_] [-igroup _ig_name_ [_ig_name ..._]] [{ -reserve | -noreserve }][-fstype _type_] [-vmtype _type_]`



 a| 
`snapdrive storage create {-lvol | -hostvol} _file_spec_ [{-dg | -vg} dg_name]{-dgsize | -vgsize} _size_-filervol _long_filer_path_ [-devicetype {shared | dedicated}] [{-noreserve | -reserve}] [-fstype _type_] [-vmtype _type_]`



 a| 
`snapdrive storage create -fs _file_spec_ -nolvm [-fsopts options ] [-mntopts options] [-nopersist] { -lun _long_lun_name_ | -filervol _long_filer_path_ } -lunsize _size_ [-igroup _ig_name_ [_ig_name ..._]] [{ -reserve | -noreserve }] [-devicetype {shared | dedicated}] [-fstype _type_] [-vmtype _type_]`



 a| 
`snapdrive storage create _host_lvm_fspec_ -filervol _long_filer_path_ -dgsize _size_ [-igroup _ig_name_ [_ig_name ..._]] [{ -reserve | -noreserve }] [-devicetype {shared | dedicated}]`



 a| 
`snapdrive storage create _host_lvm_fspec_ -lun _long_lun_name_ [_lun_name ..._] -lunsize _size_ [-igroup _ig_name_ [_ig_name ..._]] [{ -reserve | -noreserve }]`

[NOTE]
====
Puede utilizar cualquiera de los formatos para `-file_spec` argumento, en función del tipo de almacenamiento que se desee crear. (Recuerde eso `-dg` es un sinónimo de `-vg`, y. `-hostvol` es un sinónimo de `-lvol`.)

Para crear un sistema de archivos directamente en una LUN, utilice este formato: `-fs _file_spec_ [-nolvm -fs _type_] [-fsops _options_] [-mntopts _options_] [-vmtype _type_]`

Para crear un sistema de archivos que utilice un grupo de discos o un volumen de host, utilice el siguiente formato: `-fs _file_spec_ [-fstype _type_] [-fsopts _options_] [-mntops _options_] [-hostvol _file_spec_] [-dg _dg_name_] [-vmtype _type_]`

Para crear un volumen lógico o de host, se debe usar el siguiente formato: `[-hostvol _file_spec_] [-dg _dg_name_] [-fstype _type_] [-vmtype _type_]`

Para crear un grupo de discos, utilice este formato: `-dg _dg_name_ [-fstype _type_] [-vmtype _type_]`

====


 a| 
Conecte
 a| 
`snapdrive storage connect -fs _file_spec -nolvm_ -lun _long_lun_name_ [-igroup _ig_name_ [_ig_name ..._]] [-nopersist] [-mntopts options] [-devicetype {shared | dedicated}][-fstype _type_] [-vmtype _type_]`



 a| 
`snapdrive storage connect -fs _file_spec_ -hostvol _file_spec_ -lun _long_lun_name_ [_lun_name ..._] [-igroup _ig_name_ [_ig_name ..._]][-nopersist] [-mntopts options] [-devicetype {shared | dedicated}][-fstype _type_] [-vmtype _type_]`



 a| 
`snapdrive storage connect -lun _long_lun_name_ [_lun_name ..._][-igroup _ig_name_ [_ig_name ..._]][-vmtype _type_]`



 a| 
`snapdrive storage connect -lun _long_lun_name_ [_lun_name..._][-devicetype {shared | dedicated}][-vmtype _type_]`



 a| 
`snapdrive storage connect -fs _file_spec_ {-hostvol | -lvol} _file_spec_ -lun _long_lun_name_ [_lun_name..._] [-devicetype {shared | dedicated}] [-nopersist] [-mntopts options] [-fstype _type_] [-vmtype _type_]`



 a| 
Desconectar
 a| 
`snapdrive storage disconnect -lun _long_lun_name_ [_lun_name..._] [-devicetype {shared | dedicated}][-vmtype _type_]`



 a| 
`snapdrive storage disconnect {-vg | -dg | -fs | -lvol | -hostvol} _file_spec_ [_file_spec ..._] [{-vg | -dg | -fs | -lvol | -hostvol} _file_spec_ ...] ...] [-full] [-devicetype {shared | dedicated}][-fstype _type_] [-vmtype _type_]`



 a| 
Cambie el tamaño
 a| 
`snapdrive storage resize {-dg | -vg} _file_spec_ [_file_spec ..._]{-growby | -growto} _size_ [_-addlun_ [-igroup _ig_name_ [_ig_name ..._]]] [{ -reseserve | -noreserve }]] [-fstype _type_] [-vmtype _type_]`



 a| 
Mostrar/Lista
 a| 
`snapdrive storage { show | list } -filer _filername_ [_filername ..._] [-verbose] [-quiet] [-capabilities]`



 a| 
`snapdrive storage { show | list } -filervol _long_filer_path_ [_filer_path..._][-verbose] [-quiet] [-capabilities]`



 a| 
`snapdrive storage { show | list } {-all | device} [-devicetype {shared | dedicated}] [-capabilities]`



 a| 
`snapdrive storage show [-verbose] {-filer _filername_ [_filername..._] | -filervol _volname_ [_volname..._]} [-devicetype {shared | dedicated}] [-capabilities]`



 a| 
`snapdrive storage { show| list } -lun _long_lun_name_ [_lun_name ..._] [-verbose] [-quiet] [-status] [-capabilities]`



 a| 
`snapdrive storage { show | list } { -vg | -dg | -fs | -lvol |-hostvol } _file_spec_ [_file_spec ..._] [{ -vg | -dg | -fs | -lvol | -hostvol } _file_spec_ [_file_spec ..._]] [-verbose] [-quiet [-fstype _type_] [-vmtype _type_] [-status] [-capabilities]`



 a| 
`snapdrive storage { show | list } { -filer _filer_name_ [_filer_name ..._] | -filervol _long_filer_path_ [_filer_path ..._] } [-verbose] [-devicetype {shared | dedicated}] [-capabilities] [-quiet]`



 a| 
`snapdrive storage { show | list } -lun _long_lun_name_ [_lun_name ..._] [-verbose] [-status] [-fstype _type_] [-vmtype _type_] [-capabilities] [-quiet]`



 a| 
Eliminar
 a| 
`snapdrive storage delete [-lun] _long_lun_name_ [_lun_name..._] [-devicetype {shared | dedicated}] [-fstype _type_] [-vmtype _type_]`



 a| 
`snapdrive storage delete [-vg | -dg | -fs | -lvol | -hostvol] _file_spec_ [_file_spec ..._] [{-vg | -dg | -fs | -lvol | -hostvol} _file_spec_ [_file_spec ..._] ...] [-full] [-devicetype {shared | dedicated}]] [-fstype _type_] [-vmtype _type_]`

|===
*Información relacionada*

xref:reference_command_line_arguments.adoc[Argumentos de la línea de comandos]
