---
permalink: solaris/task_setting_up_an_sfrac_i_o_fencing_environment_on_a_storage_system.html 
sidebar: sidebar 
keywords: snap, snapdrive, sfrac, fencing, environment, storage 
summary: SnapDrive para UNIX ofrece opciones de aprovisionamiento de almacenamiento y gestión de Snapshot para gestionar grupos de discos locales, nodos y compartidos de todo el clúster host, así como sistemas de archivos en un entorno SFRAC. 
---
= Configurar un entorno de delimitación de I/o SFRAC en un sistema de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive para UNIX ofrece opciones de aprovisionamiento de almacenamiento y gestión de Snapshot para gestionar grupos de discos locales, nodos y compartidos de todo el clúster host, así como sistemas de archivos en un entorno SFRAC.

.Pasos
. Configuración `rsh` o. `ssh` usar manualmente el símbolo de acceso sin contraseña para el usuario raíz en todos los nodos del clúster de hosts.
+
Para obtener instrucciones de configuración, consulte la _Veritas Cluster Server Installation Guide para Solaris_.

. Instale SnapDrive para UNIX en todos los nodos del clúster de host.
+
Si se instalan diferentes versiones de SnapDrive para UNIX en nodos diferentes, se produce un error en las operaciones de SnapDrive para UNIX.

. Compruebe la conectividad FC entre los sistemas de almacenamiento.
+
Para obtener información acerca de los requisitos de hardware para los hosts, consulte SFRAC _Release Notes_.

+

NOTE: La `/opt/NTAPsnapdrive/snapdrive.conf` en todos los nodos debe tener el `default-transport` Variable de configuración establecida en FCP.

. Establezca un valor para `_secure-communication-among-cluster-nodes_` variable de configuración, para asegurarse de que `rsh` o. `ssh` access-without-password-prompt para el usuario raíz se configura para todos los nodos del clúster.
+
Este valor es necesario porque si inicia los comandos de SnapDrive para UNIX desde cualquier nodo (maestro o no maestro) en el clúster de hosts, SnapDrive para UNIX realiza operaciones en otros nodos del clúster de hosts.

. Compruebe la detección de dispositivos en los nodos del clúster de hosts. Para ello, ejecute el siguiente comando en cada nodo del clúster de hosts:
+
`*snapdrive storage create -lun _long_lun_name_ [_lun_name..._] -lunsize size [{_-reserve_ | _-noreserve_}] [_-igroup ig_name_ [_ig_name ..._]]*`

+
[listing]
----

	# snapdrive storage create -lun f270-197-109:/vol/vol2/luntest -lunsize 20m

		LUN f270-197-109:/vol/vol2/luntest ... created

		mapping new lun(s) ... done
		discovering new lun(s) ... done

		LUN to device file mappings:
	-f270-197-109:/vol/vol2/luntest => /dev/vx/dmp/c5t0d6s2

	# snapdrive storage delete -lun f270-197-109:/vol/vol2/luntest -lunsize 20m
	- LUN f270-197-109:/vol/vol2/luntest ... deleted
----

