---
permalink: solaris/task_connecting_tosnapshot_copies_ofshared_storageentities_other_thanluns.html 
sidebar: sidebar 
keywords: snap, snapdrive, connect, snapshot, copy, shared, storage, lun 
summary: Puede utilizar el comando SnapDrive snap connect para conectar a una copia Snapshot de entidades de almacenamiento compartido que no sean las LUN. 
---
= Conectarse a las copias Snapshot de entidades de almacenamiento compartido distintas de LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `snapdrive snap connect` Comando para conectarse a una copia Snapshot de entidades de almacenamiento compartido distintas de las LUN.

.Pasos
. Introduzca el siguiente comando:
+
`*snapdrive snap connect _fspec_set_ [_fspec_set..._] -snapname _long_snap_name_ [-devicetype shared] [-split]*`

+
En esta sintaxis, `_fspec_set_` es: `{-dg | -fs}_src_file_spec_ [_dest_file_spec_ ] [-destdg _dgname_]`



El siguiente ejemplo se conecta a una copia Snapshot que contiene entidades de almacenamiento compartidas en un clúster de hosts de origen. La operación se ejecuta desde el nodo que no es maestro de clústeres, pero el comando se envía al nodo maestro y se ejecuta:

[listing]
----
# snapdrive snap connect -fs /mnt/sfortesting /mnt/sfortesting2 -
snapname f270-
197-109:/vol/vol2:testsfarcsnap -devicetype shared -autorename
Execution started on cluster master: sfrac-57
connecting sfortesting_SdDg:
LUN copy sfortesting_SdLun_0 ... created
(original: f270-197-109:/vol/vol2/sfortesting_SdLun)
mapping new lun(s) ... done
discovering new lun(s) ... done
Connecting cluster node: sfrac-58 mapping lun\(s\) ... done
discovering lun(s) ... done
LUN f270-197-109:/vol/vol2/sfortesting_SdLun_0 connected
- device filename(s): /dev/vx/dmp/c3t0d22s2
Importing sfortesting_SdDg_0
Activating hostvol sfracvxfstestfs_SdHv_0
Successfully connected to snapshot f270-197-
109:/vol/vol2:testsfarcsnap
disk group sfortesting_SdDg_0 containing host volumes
sfortesting_SdHv_0 (filesystem: /mnt/sfortesting2)
----
El siguiente ejemplo se conecta a una copia Snapshot que contiene entidades de almacenamiento compartidas en un clúster de hosts que no es de origen. La operación se ejecuta desde el nodo que no es maestro de clústeres, pero el comando se envía al nodo maestro y se ejecuta:

[listing]
----
# snapdrive snap connect -fs /mnt/sfortesting -snapname f270-197-
109:/vol/vol2:testsfarcsnap -devicetype shared
Execution started on cluster master: sfrac-57
connecting sfortesting_SdDg:
LUN copy sfortesting_SdLun_0 ... created
(original: f270-197-109:/vol/vol2/sfortesting_SdLun)
Step Action
184 Connecting to a Snapshot copy
mapping new lun(s) ... done
discovering new lun(s) ... done
Connecting cluster node: sfrac-58
mapping lun(s) ... done
discovering lun(s) ... done
LUN f270-197-109:/vol/vol2/sfortesting_SdLun_0 connected
- device filename(s): /dev/vx/dmp/c3t0d1s2
Importing sfortesting_SdDg
Activating hostvol sfortesting_SdHv
Successfully connected to snapshot f270-197-
109:/vol/vol2:testsfarcsnap
disk group sfortesting_SdDg containing host volumes
sfortesting_SdHv (filesystem: /mnt/sfortesting)
----