---
permalink: linux-installation-cmode/task_connecting_linux_host_to_the_storage_system.html 
sidebar: sidebar 
keywords: snapdrive, snap, connect, hosts, storage, system 
summary: 'Para que las operaciones de SnapDrive para UNIX se realicen correctamente, debe configurar sus máquinas virtuales de almacenamiento \(SVM, antes denominadas Vserver\)' 
---
= Conectar los hosts Linux a los sistemas de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para que las operaciones de SnapDrive para UNIX se realicen correctamente, debe configurar sus máquinas virtuales de almacenamiento (SVM, antes denominadas Vserver).

* Debe haber asignado los agregados que contienen volúmenes a la lista de agregados de SVM para ejecutar las operaciones de SnapDrive para UNIX.
* Debe haber creado una o más SVM para servir datos del clúster.
+
La dirección IP de la interfaz lógica de gestión (LIF) de SVM debe asignarse con el nombre de SVM, ya sea en el servicio de nombres de dominio (DNS) o en la `/etc/hosts` archivo.



.Pasos
. Si ejecuta ONTAP 8.2.2 o una versión anterior, cree un usuario en el servidor de gestión de clústeres, también denominado adminSVM: +
+
`*snapdrive config set -cserver _csadmin_name cserver_name_*`

+
Si está ejecutando ONTAP 8.2.3 o posterior, omita este paso.

. Cree un usuario en la SVM de datos:
+
`*snapdrive config set vsadmin_name _Vserver_name_*`

+

NOTE: `_Vserver_name_` Es el nombre de la SVM y se debe asignar a la dirección IP de LIF de gestión.

. Compruebe que la SVM esté configurada en SnapDrive para UNIX:
+
`*snapdrive config list*`

+
El comando enumera el nombre de usuario y la dirección IP del servidor de gestión de clústeres y la SVM de datos.

. Modifique la ruta de la interfaz de gestión a la ruta de interfaz de datos de la SVM:
+
`*snapdrive config set -mgmtpath _management_interface_path data_interface_path_*`

. Compruebe que todas las interfaces de gestión y datos están configuradas correctamente:
+
`*snapdrive config list -mgmtpath*`


